//! The public seam of the core.
//!
//! Everything in this module is the schema authority for three things at once:
//!
//! 1. the FFI surface (UniFFI → Kotlin, napi-rs → Node) — commands, queries and
//!    events cross the seam as JSON strings and the platform side gets typed
//!    bindings generated by `typeshare` from these definitions;
//! 2. the Connect wire protocol (JSON over WebSocket), see [`crate::connect::wire`];
//! 3. everything persisted that isn't a mirror table (session document, saved
//!    queues, settings, config backup).
//!
//! Rules for this file:
//! - Every type is `#[typeshare]` and `serde` round-trippable. Enums with data use
//!   adjacent tagging (`tag = "type", content = "data"`) because typeshare needs it.
//! - No `u64`/`i64` (TypeScript can't represent them). Milliseconds are `u32`
//!   for durations/positions, `f64` for epoch timestamps.
//! - No tuples, no `serde_json::Value`. Opaque JSON travels as a `String`.
//! - Additive changes only once shipped: new fields are `Option` or have
//!   `#[serde(default)]`, and unknown fields are preserved by the document
//!   types that carry `extra` (older devices must round-trip newer state).
//! - `Option` fields serialise as `null`, never as an absent key (serde's
//!   default, and nothing here uses `skip_serializing_if` on an `Option`).
//!   TypeScript consumers should test `== null`, not `in` / `undefined`.
//! - Local paths (`MediaSessionMetadata::artwork_path`, `QueryResult::Path`)
//!   are plain filesystem paths without a scheme; `MediaSource::url` is the
//!   one place a `file://` URL travels.
//!
//! The core is an actor: [`Command`]s in, [`Event`]s out, [`Query`]s are async
//! request/response and never expose interior state synchronously.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use typeshare::typeshare;

/// Schema version of everything in this file. Bump on incompatible change;
/// additive changes don't need it.
pub const API_SCHEMA_VERSION: u32 = 1;
/// Protocol floor below which the Connect handshake refuses to talk.
/// Aliases of the wire constants so the two can never drift apart.
pub const PROTOCOL_MIN_VERSION: u32 = crate::connect::wire::PROTOCOL_MIN;
/// Connect wire protocol spoken by this build (2 added mutual LAN auth).
pub const PROTOCOL_VERSION: u32 = crate::connect::wire::PROTOCOL;

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

#[typeshare]
pub type ServerId = String;
#[typeshare]
pub type TrackId = String;
#[typeshare]
pub type AlbumId = String;
#[typeshare]
pub type ArtistId = String;
#[typeshare]
pub type PlaylistId = String;
#[typeshare]
pub type DeviceId = String;
#[typeshare]
pub type SessionId = String;
#[typeshare]
pub type JobId = String;
#[typeshare]
pub type FilterId = String;
/// Unique per queue *instance* of a track: the same track queued twice has two keys.
#[typeshare]
pub type QueueKey = String;
/// Epoch milliseconds, on the local monotonic-ish wall clock unless stated otherwise.
#[typeshare]
pub type EpochMs = f64;
/// Duration or position in milliseconds.
#[typeshare]
pub type Ms = u32;

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CoreConfig {
    /// Root for the SQLite mirror, downloads, caches, logs. Created if missing.
    pub data_dir: String,
    /// Separate directory for the evictable stream cache (may be on a different volume).
    pub cache_dir: String,
    pub device_id: DeviceId,
    pub device_name: String,
    pub platform: Platform,
    pub app_version: String,
    /// Whether this process owns audio itself (`native-audio` feature; desktop) or
    /// drives an external backend through [`Event::Backend`] (Android / Media3).
    pub audio: AudioMode,
    /// Present when running as the headless coordinator. The coordinator never
    /// plays audio and never holds credentials.
    #[serde(default)]
    pub coordinator_listen: Option<String>,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum Platform {
    Android,
    Linux,
    MacOs,
    Windows,
    Coordinator,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum AudioMode {
    /// Symphonia + cpal inside the core.
    Native,
    /// Platform player (ExoPlayer) driven over the seam.
    External,
    /// No audio at all (coordinator, tests).
    None,
}

// ---------------------------------------------------------------------------
// Library entities (rows of the local mirror, shaped for the UI)
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ReplayGain {
    pub track_gain_db: Option<f64>,
    pub track_peak: Option<f64>,
    pub album_gain_db: Option<f64>,
    pub album_peak: Option<f64>,
}

/// Sonic analysis attributes (AudioMuse / `sonicSimilarity`). All optional.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SonicAttributes {
    pub bpm: Option<f64>,
    pub key: Option<String>,
    pub energy: Option<f64>,
    pub mood: Option<String>,
    pub danceability: Option<f64>,
    pub valence: Option<f64>,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub enum OfflineState {
    #[default]
    None,
    /// In the evictable stream cache.
    Cached,
    /// Pinned download, never evicted.
    Downloaded,
    Downloading,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct Track {
    pub id: TrackId,
    pub server_id: ServerId,
    pub title: String,
    pub album_id: Option<AlbumId>,
    pub album: Option<String>,
    pub artist_id: Option<ArtistId>,
    pub artist: Option<String>,
    pub album_artist: Option<String>,
    pub track_number: Option<u32>,
    pub disc_number: Option<u32>,
    pub year: Option<u32>,
    pub genre: Option<String>,
    pub duration_ms: Ms,
    pub bit_rate: Option<u32>,
    pub sample_rate: Option<u32>,
    pub bit_depth: Option<u32>,
    pub channels: Option<u32>,
    pub suffix: Option<String>,
    pub content_type: Option<String>,
    pub size_bytes: Option<f64>,
    pub path: Option<String>,
    pub cover_art: Option<String>,
    /// 0 = unrated. Subsonic ratings are integers 1–5.
    pub rating: u32,
    pub loved: bool,
    pub play_count: u32,
    pub last_played: Option<EpochMs>,
    pub created: Option<EpochMs>,
    pub replay_gain: Option<ReplayGain>,
    pub sonic: Option<SonicAttributes>,
    pub offline: OfflineState,
    pub music_brainz_id: Option<String>,
    pub explicit: bool,
    pub comment: Option<String>,
}

/// Compact track for queue views and lists that don't need everything.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct TrackSummary {
    pub id: TrackId,
    pub server_id: ServerId,
    pub title: String,
    pub artist: Option<String>,
    pub album: Option<String>,
    pub album_id: Option<AlbumId>,
    pub artist_id: Option<ArtistId>,
    pub duration_ms: Ms,
    pub cover_art: Option<String>,
    pub rating: u32,
    pub loved: bool,
    pub offline: OfflineState,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct Album {
    pub id: AlbumId,
    pub server_id: ServerId,
    pub name: String,
    pub artist_id: Option<ArtistId>,
    pub artist: Option<String>,
    pub year: Option<u32>,
    pub genre: Option<String>,
    pub song_count: u32,
    pub duration_ms: Ms,
    pub cover_art: Option<String>,
    pub rating: u32,
    pub loved: bool,
    pub play_count: u32,
    pub created: Option<EpochMs>,
    pub last_played: Option<EpochMs>,
    pub is_compilation: bool,
    pub music_brainz_id: Option<String>,
    pub replay_gain: Option<ReplayGain>,
    pub offline: OfflineState,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct Artist {
    pub id: ArtistId,
    pub server_id: ServerId,
    pub name: String,
    pub album_count: u32,
    pub song_count: u32,
    pub cover_art: Option<String>,
    pub artist_image_url: Option<String>,
    pub loved: bool,
    pub music_brainz_id: Option<String>,
    pub biography: Option<String>,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct Playlist {
    pub id: PlaylistId,
    pub server_id: ServerId,
    pub name: String,
    pub comment: Option<String>,
    pub owner: Option<String>,
    pub public: bool,
    pub song_count: u32,
    pub duration_ms: Ms,
    pub cover_art: Option<String>,
    pub created: Option<EpochMs>,
    pub changed: Option<EpochMs>,
    /// Smart (rules-driven) playlists are read-only: no reorder, no manual add.
    pub is_smart: bool,
    /// True when the authenticated user owns it (needed for smart-playlist ownership UI).
    pub is_mine: bool,
    pub offline: OfflineState,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct Genre {
    pub name: String,
    pub song_count: u32,
    pub album_count: u32,
}

// ---------------------------------------------------------------------------
// Server
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ServerCapabilities {
    pub server_version: Option<String>,
    pub open_subsonic: bool,
    /// Raw extension names from `getOpenSubsonicExtensions`.
    pub extensions: Vec<String>,
    pub transcode_offset: bool,
    pub form_post: bool,
    pub song_lyrics: bool,
    pub sonic_similarity: bool,
    pub api_key_authentication: bool,
    pub transcoding_extension: bool,
    /// Navidrome native API reachable (undocumented, behind a flag).
    pub native_api: bool,
    /// Whether the version meets the 0.63.0 floor.
    pub meets_floor: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ServerInfo {
    pub id: ServerId,
    pub url: String,
    pub username: String,
    pub name: String,
    pub capabilities: ServerCapabilities,
    pub last_sync: Option<EpochMs>,
    pub reachable: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct TranscodingProfile {
    /// `None` means original.
    pub format: Option<String>,
    pub max_bit_rate: Option<u32>,
    /// Container/codec suffixes this device cannot decode natively; the core
    /// forces a transcode for them regardless of the bitrate preference.
    pub cannot_decode: Vec<String>,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub enum NetworkKind {
    Wifi,
    Cellular,
    Wired,
    Offline,
    Unknown,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NetworkState {
    pub kind: NetworkKind,
    pub metered: bool,
    /// Opaque id (SSID hash etc.) so profiles can vary per network.
    pub network_id: Option<String>,
}

// ---------------------------------------------------------------------------
// Session document
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum ContextKind {
    Album {
        id: AlbumId,
    },
    Artist {
        id: ArtistId,
    },
    Playlist {
        id: PlaylistId,
    },
    Genre {
        name: String,
    },
    Filter {
        filter: Filter,
    },
    /// Search results, an arbitrary selection, "all songs". Stores its track list.
    AdHoc {
        label: String,
    },
    Autoplay,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub enum SortOrder {
    #[default]
    Default,
    Title,
    Artist,
    Album,
    Year,
    DateAdded,
    Rating,
    PlayCount,
    Duration,
    Random,
    Bpm,
    Energy,
}

/// What is being played. The visible queue is derived from this plus the cursor,
/// the shuffle permutation and the insertion list — never stored flat.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct QueueContext {
    pub server_id: ServerId,
    pub kind: ContextKind,
    pub label: String,
    pub sort: SortOrder,
    /// Resolved track order. Present in the live document; snapshots omit it
    /// for ID-referenced contexts and re-resolve on restore.
    #[serde(default)]
    pub tracks: Vec<TrackId>,
}

/// Where a queue item came from. Persists so previous/next stay inverses and
/// the UI can show "from playlist" vs "queued" vs "autoplay".
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum QueueSource {
    /// Index into the context's *unshuffled* track list.
    Context { index: u32 },
    /// Play next / play later.
    Inserted,
    Autoplay {
        provider: AutoplayProvider,
        reason: String,
        score: Option<f64>,
    },
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct QueueItem {
    pub key: QueueKey,
    pub track_id: TrackId,
    pub source: QueueSource,
    /// Marked when a device could not play it; skipped, never scrobbled.
    #[serde(default)]
    pub unavailable: bool,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub enum QueueMode {
    /// Insertions live in a separate "Playing Next" list ahead of the context.
    #[default]
    Apple,
    /// Insertions splice into the context order after the cursor.
    YouTube,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub enum RepeatMode {
    #[default]
    Off,
    /// Loops the context only.
    All,
    /// Repeats whatever is playing, regardless of where it came from.
    One,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ShuffleState {
    /// The permutation is derived deterministically from the seed over the
    /// context length, so it costs 4 bytes to store and sync.
    pub seed: u32,
    /// Unshuffled context index pinned to permuted position 0: the item that
    /// was current when shuffle was enabled, so it keeps its place.
    #[serde(default)]
    pub anchor: Option<u32>,
    /// Explicit permutation (a bijection over `0..tracks.len()`). Only present
    /// after a structural edit while shuffled (remove, move, YouTube-mode
    /// splice), where a seed alone can no longer express the order without
    /// rescrambling what the user already saw. Takes precedence over `seed`
    /// when present and valid; cleared by a reshuffle.
    #[serde(default)]
    pub order: Option<Vec<u32>>,
}

/// Last known transport sample. Receivers extrapolate; it is never sent on a timer.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct PositionStamp {
    pub position_ms: Ms,
    /// Session clock (coordinator time when connected, local otherwise).
    pub taken_at: EpochMs,
    pub rate: f64,
    pub is_playing: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct TransportLease {
    pub owner: Option<DeviceId>,
    /// Fencing token, increments on every ownership change.
    pub epoch: u32,
    pub expires_at: EpochMs,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct TransportState {
    pub lease: TransportLease,
    pub position: PositionStamp,
    pub buffering: bool,
    /// Accumulated played time of the current item; travels with handoff so a
    /// takeover 90 s in doesn't eat the scrobble.
    pub played_ms: Ms,
    pub volume: f64,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SavedQueue {
    pub id: String,
    pub context: QueueContext,
    pub label: String,
    pub cursor: u32,
    pub current: Option<QueueItem>,
    pub history: Vec<QueueItem>,
    pub insertions: Vec<QueueItem>,
    pub shuffle: Option<ShuffleState>,
    pub repeat: RepeatMode,
    pub position_ms: Ms,
    pub pinned: bool,
    pub created_at: EpochMs,
    /// Played from or restored. Drives LRU eviction.
    pub last_interacted_at: EpochMs,
    /// LWW clock for sync.
    pub updated_at: EpochMs,
    pub track_count: u32,
    pub cover_art: Option<String>,
}

/// The unit of state. Small, serialisable, synced, snapshotted, undone.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SessionDocument {
    pub schema_version: u32,
    pub session_id: SessionId,
    /// Navidrome identity the session is scoped to: `serverId:username`.
    pub scope: String,
    /// Monotonic; every op targets a revision and is rejected if stale.
    pub revision: u32,
    pub updated_at: EpochMs,
    pub context: Option<QueueContext>,
    pub mode: QueueMode,
    /// Index into the *permuted* context order of the current context item.
    pub cursor: u32,
    pub current: Option<QueueItem>,
    /// Already played, still reachable. Capped (~200).
    pub history: Vec<QueueItem>,
    /// Play next / play later, in order.
    pub insertions: Vec<QueueItem>,
    pub shuffle: Option<ShuffleState>,
    pub repeat: RepeatMode,
    pub autoplay: bool,
    pub transport: TransportState,
    pub saved_queues: Vec<SavedQueue>,
    /// Unknown fields from newer schema versions, preserved verbatim as JSON.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extra: HashMap<String, String>,
}

// ---------------------------------------------------------------------------
// Derived queue view (what the UI renders)
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct QueueEntry {
    pub item: QueueItem,
    pub track: TrackSummary,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct QueueView {
    pub context_label: Option<String>,
    pub history: Vec<QueueEntry>,
    pub current: Option<QueueEntry>,
    /// From the insertion list.
    pub playing_next: Vec<QueueEntry>,
    /// Continuing from the context, in permuted order.
    pub upcoming: Vec<QueueEntry>,
    pub shuffle: bool,
    pub repeat: RepeatMode,
    pub autoplay: bool,
    pub mode: QueueMode,
    pub total_upcoming: u32,
}

// ---------------------------------------------------------------------------
// Filters (superset of NSP vocabulary)
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub enum FilterField {
    Title,
    Album,
    Artist,
    AlbumArtist,
    Genre,
    Year,
    DateAdded,
    DateModified,
    LastPlayed,
    PlayCount,
    Rating,
    Loved,
    Duration,
    BitRate,
    FilePath,
    FileType,
    Comment,
    Lyrics,
    HasCoverArt,
    Compilation,
    DiscNumber,
    TrackNumber,
    Bpm,
    Key,
    Energy,
    Mood,
    // Local-only fields (not server-expressible):
    Downloaded,
    Cached,
    /// Playable with no network: downloaded or fully in the stream cache.
    AvailableOffline,
    LocalPlayCount,
    LocalLastPlayed,
    InPlaylist,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub enum FilterOp {
    Is,
    IsNot,
    Contains,
    NotContains,
    StartsWith,
    EndsWith,
    Gt,
    Lt,
    InTheRange,
    Before,
    After,
    InTheLast,
    NotInTheLast,
    IsTrue,
    IsFalse,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum FilterValue {
    Text(String),
    Number(f64),
    Range { low: f64, high: f64 },
    Date(String),
    Bool(bool),
    Days(u32),
    List(Vec<String>),
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FilterRule {
    pub field: FilterField,
    pub op: FilterOp,
    pub value: FilterValue,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum FilterNode {
    Rule(FilterRule),
    All(Vec<FilterNode>),
    Any(Vec<FilterNode>),
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Filter {
    pub id: FilterId,
    pub name: String,
    pub root: FilterNode,
    pub sort: SortOrder,
    pub descending: bool,
    pub limit: Option<u32>,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FilterCapability {
    /// Every rule is expressible as NSP.
    pub server_expressible: bool,
    /// Fields that block server expression.
    pub local_only_fields: Vec<FilterField>,
}

// ---------------------------------------------------------------------------
// Autoplay
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub enum AutoplayProvider {
    SonicSimilarity,
    SimilarSongs,
    TopSongs,
    Random,
    SavedFilter,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AutoplaySettings {
    pub chain: Vec<AutoplayProvider>,
    pub seed_window: u32,
    pub min_similarity: Option<f64>,
    pub exclusion_window: u32,
    pub filter_id: Option<FilterId>,
}

// ---------------------------------------------------------------------------
// Immersive artwork (how the full player shows a cover; `crate::artwork`)
// ---------------------------------------------------------------------------

/// How the full player shows a cover along one of its edges.
#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ArtworkStyle {
    /// Edge to edge, continued past the edge by a flipped copy that blurs and fades with distance.
    Mirror,
    /// Edge to edge, continued past the edge by the colours along it ([`ArtworkEdge::edge_colors`]).
    Extend,
    /// A rounded card on the artwork's blurred colours (the player as it was).
    Card,
}

/// The `display.immersiveArtwork` setting.
#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub enum ImmersiveArtwork {
    /// Mirror or extend where the cover suits it, a card otherwise.
    #[default]
    Automatic,
    /// Mirror or extend every square cover.
    Always,
    /// Always a card.
    Never,
}

/// A detected face, as fractions of the image's width and height (origin top left).
#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct FaceRect {
    pub x: f64,
    pub y: f64,
    pub w: f64,
    pub h: f64,
}

/// The app's theme, for [`ArtworkLayoutRequest::theme`].
#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ArtworkTheme {
    Dark,
    Light,
}

/// What the platform hands [`crate::artwork::layout`] beside the pixels.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ArtworkLayoutRequest {
    #[serde(default)]
    pub faces: Vec<FaceRect>,
    #[serde(default)]
    pub preference: ImmersiveArtwork,
    /// The app's theme: the controls follow it (light in dark mode, dark in light mode) unless
    /// what sits behind them is almost all dark or all light, when they follow that. Without it,
    /// whichever controls need the lighter scrim.
    #[serde(default)]
    pub theme: Option<ArtworkTheme>,
}

/// The measurements a decision was made from (for tuning and the debug grid).
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ArtworkMetrics {
    /// Share of the edge strip within a small colour distance of its median (1 = one flat colour).
    pub flat: f64,
    /// Mean colour distance of the edge strip from its own column colours (0 = every column is one colour).
    pub drift: f64,
    /// How much the column colours change from one column to the next.
    pub rough: f64,
    /// Small high-contrast shapes (text, logos, stickers) in the zone a reflection shows sharply.
    pub marks: u32,
    /// Mean colour change between neighbouring pixels in the lower 40%.
    pub busy: f64,
    pub faces: u32,
    /// Share of what sits behind the controls (the continuation) that is very dark / very light
    /// (one of them near 1: the controls follow it, not the theme).
    #[serde(default)]
    pub dark_share: f64,
    #[serde(default)]
    pub light_share: f64,
}

/// How to show the cover with the continuation along one edge (bottom for a portrait layout, right
/// for a landscape one). Colours are `0xRRGGBB`.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ArtworkEdge {
    pub style: ArtworkStyle,
    /// The colours along the edge, sampled evenly (left to right for the bottom edge, top to bottom
    /// for the right edge): what [`ArtworkStyle::Extend`] carries on. All one colour when the edge is flat.
    pub edge_colors: Vec<u32>,
    /// What the continuation fades into, far from the artwork.
    pub base_color: u32,
    /// Dark text and controls over the continuation (it is light); light ones otherwise.
    pub light: bool,
    /// The opacity of the scrim (black under light text, white under dark text) that the controls
    /// need over the continuation to reach 4.5:1.
    pub scrim: f64,
    /// Why this style, e.g. `mirror`, `extend:flat`, `card:marks` (debugging and tuning). The apps
    /// read one: `extend:flat` means the artwork already ends in one colour, carried on with a
    /// crisp edge (no fade, no blur); any other extension (`extend:plain`, `extend:columns`, …)
    /// fades in.
    pub reason: String,
    pub metrics: ArtworkMetrics,
}

/// The full player's artwork layout for one cover.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ArtworkLayout {
    /// Art on top, continued downwards (phones, narrow windows).
    pub bottom: ArtworkEdge,
    /// Art on the left, continued to the right (wide windows).
    pub right: ArtworkEdge,
    /// The top strip (under the status bar and the player's header) is light: dark icons there.
    pub top_light: bool,
    /// Text or a logo sits in the top strip: start the artwork below the status bar.
    pub top_marks: bool,
}

// ---------------------------------------------------------------------------
// Lyrics (renderable model adapted from OpenSubsonic v2 structured lyrics)
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum LyricsTier {
    Syllable,
    Line,
    Unsynced,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LyricSyllable {
    pub text: String,
    pub start_ms: Ms,
    pub end_ms: Ms,
    /// No space follows this syllable (mid-word).
    pub joined: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LyricLine {
    pub start_ms: Option<Ms>,
    pub end_ms: Option<Ms>,
    pub text: String,
    /// Empty for line-level or unsynced tiers. Never fabricated.
    pub syllables: Vec<LyricSyllable>,
    /// Agent / voice id for duets and call-and-response.
    pub agent: Option<String>,
    /// Background vocal ("sub-voice") line.
    pub background: bool,
    pub translation: Option<String>,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LyricsAgent {
    pub id: String,
    pub name: Option<String>,
    /// Alignment hint: 0 = left (primary), 1 = right (secondary).
    pub side: u32,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Lyrics {
    pub track_id: TrackId,
    pub tier: LyricsTier,
    pub lang: Option<String>,
    pub display_artist: Option<String>,
    pub display_title: Option<String>,
    pub agents: Vec<LyricsAgent>,
    pub lines: Vec<LyricLine>,
    pub source: LyricsSource,
    /// Per-track user offset applied on top of timing, stored locally.
    pub offset_ms: i32,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum LyricsSource {
    Server,
    External,
    Embedded,
}

// ---------------------------------------------------------------------------
// Jobs and problems
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum JobKind {
    LibrarySync,
    BulkRating,
    BulkLove,
    Download,
    PlaylistImport,
    OutboxFlush,
    ArtworkPrefetch,
    LyricsPrefetch,
    FilterMaterialise,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum JobState {
    Queued,
    Running,
    Paused,
    Done,
    /// Finished with problems; see [`Problem`].
    Failed,
    Cancelled,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Job {
    pub id: JobId,
    pub kind: JobKind,
    pub label: String,
    pub state: JobState,
    pub done: u32,
    pub total: Option<u32>,
    pub failed: u32,
    pub created_at: EpochMs,
    pub cancellable: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Problem {
    pub id: String,
    pub job_id: Option<JobId>,
    pub summary: String,
    pub detail: Option<String>,
    pub created_at: EpochMs,
    pub retryable: bool,
}

// ---------------------------------------------------------------------------
// Connect
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DeviceInfo {
    pub id: DeviceId,
    pub name: String,
    pub platform: Platform,
    pub app_version: String,
    /// Owns transport right now.
    pub playing: bool,
    /// Ready to take over (pre-buffered) when the picker is open.
    pub ready: bool,
    pub last_seen: EpochMs,
    pub is_self: bool,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub enum ConnectionTier {
    #[default]
    Local,
    Lan,
    Coordinator,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ConnectionState {
    pub tier: ConnectionTier,
    pub connected: bool,
    pub coordinator_url: Option<String>,
    /// Estimated offset of the session clock from local, ms.
    pub clock_offset_ms: f64,
    pub round_trip_ms: Option<f64>,
    pub peer_count: u32,
    pub error: Option<String>,
}

/// A dormant "Pixel was playing X · Resume here" offer.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ResumeOffer {
    pub device_name: String,
    pub track: TrackSummary,
    pub position_ms: Ms,
    pub last_seen: EpochMs,
}

// ---------------------------------------------------------------------------
// Audio / DSP
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub enum ReplayGainMode {
    #[default]
    Off,
    Track,
    Album,
    /// Album when playing an album context, track otherwise.
    Auto,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct EqBand {
    pub frequency_hz: f64,
    pub gain_db: f64,
    pub q: f64,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct EqSettings {
    pub enabled: bool,
    pub preamp_db: f64,
    pub bands: Vec<EqBand>,
    pub preset: Option<String>,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioSettings {
    pub replay_gain: ReplayGainMode,
    pub replay_gain_preamp_db: f64,
    pub normalisation: bool,
    pub eq: EqSettings,
    pub gapless: bool,
    pub output_device: Option<String>,
    pub exclusive: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct OutputDevice {
    pub id: String,
    pub name: String,
    pub is_default: bool,
}

/// How to fetch/play one item. Given to an external backend (Android) and
/// consumed by the native backend internally.
#[typeshare]
#[derive(Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct MediaSource {
    pub key: QueueKey,
    pub track: TrackSummary,
    /// `file://` for downloads (and, for a backend without the
    /// `core_stream` capability, cached streams); otherwise either
    /// `hocket-stream://<token>` — an opaque, expiring capability the
    /// backend reads through the core's stream reader (open at an offset,
    /// read, close; no credentials involved) — or, for a backend without
    /// that capability, the server's `https://` stream URL (auth in query).
    pub url: String,
    pub headers: HashMap<String, String>,
    pub mime_type: Option<String>,
    /// Gain to apply in dB after ReplayGain/normalisation. External backends apply this.
    pub gain_db: f64,
    pub transcoded: bool,
}

/// A URL with its query string (where Subsonic carries the auth token) and
/// fragment removed, for logs.
pub fn redact_url(url: &str) -> String {
    let end = url.find(['?', '#']).unwrap_or(url.len());
    url[..end].to_string()
}

impl std::fmt::Debug for MediaSource {
    /// The stream URL is logged without its query string: it carries the
    /// auth token and salt.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MediaSource")
            .field("key", &self.key)
            .field("track", &self.track)
            .field("url", &redact_url(&self.url))
            .field("headers", &self.headers.keys().collect::<Vec<_>>())
            .field("mime_type", &self.mime_type)
            .field("gain_db", &self.gain_db)
            .field("transcoded", &self.transcoded)
            .finish()
    }
}

/// Commands the core sends to an external playback backend.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum BackendCommand {
    /// Replace what is loaded. `next` is the gapless follow-up to preload.
    Load {
        source: MediaSource,
        next: Option<MediaSource>,
        position_ms: Ms,
        play: bool,
    },
    /// Update only the preloaded follow-up.
    SetNext {
        next: Option<MediaSource>,
    },
    Play,
    Pause,
    Stop,
    Seek {
        position_ms: Ms,
    },
    SetVolume {
        volume: f64,
    },
    /// Handoff pre-buffering: fetch but don't play; discarded on timeout.
    PreBuffer {
        source: MediaSource,
        position_ms: Ms,
    },
    DiscardPreBuffer,
    SetGapless {
        enabled: bool,
    },
}

/// What an external backend reports back.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum BackendReport {
    Ready {
        key: QueueKey,
        duration_ms: Option<Ms>,
    },
    Playing {
        key: QueueKey,
        position_ms: Ms,
    },
    Paused {
        key: QueueKey,
        position_ms: Ms,
    },
    Buffering {
        key: QueueKey,
        buffering: bool,
    },
    /// Called at least every 1000 ms while playing and on every discontinuity.
    Position {
        key: QueueKey,
        position_ms: Ms,
    },
    /// Natural end; the backend has already transitioned to `next` if given.
    Ended {
        key: QueueKey,
    },
    /// Transitioned to the preloaded item (gapless).
    TransitionedToNext {
        key: QueueKey,
    },
    Error {
        key: QueueKey,
        message: String,
        fatal: bool,
    },
    PreBufferReady {
        key: QueueKey,
    },
    AudioFocusLost {
        transient: bool,
    },
    OutputDevicesChanged {
        devices: Vec<OutputDevice>,
    },
}

// ---------------------------------------------------------------------------
// Media session (OS integration)
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub enum MediaSessionAction {
    Play,
    Pause,
    Next,
    Previous,
    Seek,
    Stop,
    Shuffle,
    Repeat,
    Love,
    Rate,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct MediaSessionMetadata {
    pub title: String,
    pub artist: Option<String>,
    pub album: Option<String>,
    pub duration_ms: Ms,
    /// Local `file://` path resolved through the image cache, or `None`.
    pub artwork_path: Option<String>,
    pub track_id: Option<TrackId>,
    pub loved: bool,
    pub rating: u32,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct MediaSessionState {
    pub metadata: Option<MediaSessionMetadata>,
    pub is_playing: bool,
    pub position: PositionStamp,
    pub shuffle: bool,
    pub repeat: RepeatMode,
    pub volume: f64,
    pub actions: Vec<MediaSessionAction>,
    /// Whether this device owns transport. Remote controls still work when it
    /// doesn't; they are forwarded to the playing device.
    pub owns_transport: bool,
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum SettingScope {
    DeviceLocal,
    AccountSynced,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Setting {
    pub key: String,
    /// JSON-encoded value.
    pub value: String,
    pub scope: SettingScope,
    pub updated_at: EpochMs,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SleepTimer {
    pub ends_at: Option<EpochMs>,
    pub stop_at_end_of_track: bool,
}

// ---------------------------------------------------------------------------
// Actions and undo
// ---------------------------------------------------------------------------

/// A first-class user-visible action from the registry. Menus, palettes,
/// shortcuts, media-session buttons and undo labels are generated from these.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ActionDescriptor {
    pub id: String,
    pub label: String,
    pub icon: String,
    pub category: String,
    /// Applicable to the given selection/context (evaluated by the core).
    pub enabled: bool,
    pub default_shortcut: Option<String>,
    pub undoable: bool,
    pub destructive: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum ActionTarget {
    None,
    Tracks { ids: Vec<TrackId> },
    Albums { ids: Vec<AlbumId> },
    Artists { ids: Vec<ArtistId> },
    Playlists { ids: Vec<PlaylistId> },
    QueueItems { keys: Vec<QueueKey> },
    SavedQueue { id: String },
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct UndoState {
    pub can_undo: bool,
    pub undo_label: Option<String>,
    pub can_redo: bool,
    pub redo_label: Option<String>,
    /// Recent entries for the Android history sheet, newest first.
    pub history: Vec<UndoEntry>,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UndoEntry {
    pub id: String,
    pub label: String,
    pub device_id: DeviceId,
    pub at: EpochMs,
    /// e.g. "undid 487 of 500, 13 changed elsewhere"
    pub note: Option<String>,
    /// The action threw away the queue (played a new context, cleared it,
    /// restored a saved queue), so undoing it is worth offering loudly.
    #[serde(default)]
    pub replaces_queue: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Toast {
    pub id: String,
    pub message: String,
    /// Label for the single action button (e.g. "Undo", "Restore", "Retry").
    pub action_label: Option<String>,
    /// Command to dispatch when the button is pressed, JSON-encoded [`Command`].
    pub action_command: Option<String>,
    pub duration_ms: Ms,
    /// Set on "Undid …" / "Redid …" toasts: the [`UndoEntry`] they report on.
    #[serde(default)]
    pub undo_entry_id: Option<String>,
}

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PlayHistoryEntry {
    pub track: TrackSummary,
    pub played_at: EpochMs,
    pub played_ms: Ms,
    pub scrobbled: bool,
    pub device_id: DeviceId,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ListeningStats {
    pub period_days: u32,
    pub total_plays: u32,
    pub total_ms: f64,
    pub top_tracks: Vec<TrackSummary>,
    pub top_albums: Vec<Album>,
    pub top_artists: Vec<Artist>,
    /// 24 buckets.
    pub plays_by_hour: Vec<u32>,
    /// 7 buckets, Monday first.
    pub plays_by_weekday: Vec<u32>,
}

// ---------------------------------------------------------------------------
// Downloads
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum PinTarget {
    Track { id: TrackId },
    Album { id: AlbumId },
    Playlist { id: PlaylistId },
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Pin {
    pub target: PinTarget,
    pub label: String,
    pub cover_art: Option<String>,
    pub track_count: u32,
    pub downloaded_count: u32,
    pub bytes: f64,
    pub created_at: EpochMs,
    /// Original file or transcoded per profile.
    pub transcoded: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct StorageSummary {
    pub downloads_bytes: f64,
    /// Stream cache, complete and partial entries.
    pub cache_bytes: f64,
    pub images_bytes: f64,
    pub warn_threshold_bytes: Option<f64>,
    pub free_bytes: Option<f64>,
    /// Part of `cache_bytes` held by partial entries (byte ranges of tracks
    /// read only in part: seeks, skips, primed starts).
    #[serde(default)]
    pub partial_cache_bytes: f64,
    /// The stream cache's effective budget.
    #[serde(default)]
    pub cache_budget_bytes: f64,
    /// `true` while `storage.cacheMaxBytes` is `null` (its default; set it to
    /// `null` or reset it to go back): the budget is min(2 GiB, 10% of the
    /// cache volume's space), re-evaluated as it moves. Any number, 2 GiB
    /// included, is a fixed budget.
    #[serde(default)]
    pub cache_budget_auto: bool,
    /// Bytes players read from downloads or the stream cache (since install).
    #[serde(default)]
    pub served_from_disk_bytes: f64,
    /// Bytes fetched from the server for audio, playback and background.
    #[serde(default)]
    pub fetched_bytes: f64,
    /// Data saved: bytes served from disk that did not need a download, less
    /// what background prefetch and priming spent filling the cache.
    #[serde(default)]
    pub data_saved_bytes: f64,
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PlayContextArgs {
    pub context: QueueContext,
    /// Index into the unshuffled track list to start from.
    pub start_index: Option<u32>,
    pub shuffle: bool,
    /// Keep the outgoing queue as a saved queue (default true).
    #[serde(default = "default_true")]
    pub save_outgoing: bool,
}

fn default_true() -> bool {
    true
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum RatingTarget {
    Track { id: TrackId },
    Album { id: AlbumId },
}

/// What a [`LibraryItemState`] describes.
#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub enum LibraryItemKind {
    Track,
    Album,
    Artist,
}

/// A library item's rating and love as the mirror holds them now (see
/// [`Event::LibraryItemsChanged`]). Absolute values, so applying one twice
/// is harmless.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct LibraryItemState {
    pub kind: LibraryItemKind,
    pub id: String,
    /// 0 = unrated. Always 0 for artists (Subsonic does not rate them).
    pub rating: u32,
    pub loved: bool,
}

/// A secret supplied by the platform (a server password). Serialises as a
/// plain string; its `Debug` output is redacted so a command logged at
/// `trace` never carries the password.
#[typeshare]
#[derive(Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Secret(pub String);

impl Secret {
    /// Expose the secret. Callers must not copy it into logs or long-lived
    /// storage.
    pub fn expose(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Debug for Secret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Secret(<redacted>)")
    }
}

impl From<String> for Secret {
    fn from(s: String) -> Self {
        Secret(s)
    }
}

impl From<&str> for Secret {
    fn from(s: &str) -> Self {
        Secret(s.to_string())
    }
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum Command {
    // -- lifecycle --------------------------------------------------------
    /// First command after construction. Loads persisted state, starts subsystems.
    /// Emits [`Event::Started`] exactly once per core (a repeated `Start` behaves
    /// like `RequestSnapshot`).
    Start,
    /// Flush everything and stop. The process may exit afterwards. Platforms
    /// that need to know when the flush is done use `Core::shutdown()`.
    Shutdown,
    /// Re-emit every `*Changed` event with current state (UI (re)attach),
    /// preceded by [`Event::Snapshot`]. Never emits a second `Started`, so
    /// platforms can key one-time work (credential replay) on `Started`.
    RequestSnapshot,
    SetNetworkState {
        state: NetworkState,
    },
    /// App visibility for renderer throttling and prefetch pausing.
    SetVisibility {
        visible: bool,
        focused: bool,
    },
    SetBatterySaver {
        enabled: bool,
    },

    // -- servers ----------------------------------------------------------
    /// `url` must be `http(s)://` with a host and no embedded credentials.
    /// Naming a server that is already persisted (same url + username)
    /// installs it immediately from the stored capabilities (so downloads
    /// play offline) and probes in the background; a new server is only
    /// installed once the probe accepts the credentials.
    AddServer {
        url: String,
        username: String,
        password: Secret,
        name: Option<String>,
    },
    RemoveServer {
        server_id: ServerId,
    },
    ProbeServer {
        server_id: ServerId,
    },
    /// `full` forces a reconcile that catches deletions.
    SyncLibrary {
        server_id: ServerId,
        full: bool,
    },
    SetTranscodingProfile {
        network_id: Option<String>,
        profile: TranscodingProfile,
    },

    // -- transport --------------------------------------------------------
    Play,
    Pause,
    TogglePlay,
    Stop,
    Next,
    Previous,
    SeekTo {
        position_ms: Ms,
    },
    SeekBy {
        delta_ms: i32,
    },
    SetVolume {
        volume: f64,
    },

    // -- queue ------------------------------------------------------------
    PlayContext {
        args: PlayContextArgs,
    },
    /// Play an ad-hoc list (search results, a selection).
    PlayTracks {
        server_id: ServerId,
        track_ids: Vec<TrackId>,
        start_index: u32,
        label: String,
        shuffle: bool,
    },
    PlayNext {
        server_id: ServerId,
        track_ids: Vec<TrackId>,
    },
    PlayLater {
        server_id: ServerId,
        track_ids: Vec<TrackId>,
    },
    JumpToQueueItem {
        key: QueueKey,
    },
    RemoveQueueItems {
        keys: Vec<QueueKey>,
    },
    /// `to_index` is within the combined playing-next + upcoming list.
    MoveQueueItem {
        key: QueueKey,
        to_index: u32,
    },
    ClearQueue,
    /// Clears playing-next only.
    ClearInsertions,
    SetShuffle {
        enabled: bool,
    },
    SetRepeat {
        mode: RepeatMode,
    },
    SetAutoplay {
        enabled: bool,
    },
    SetQueueMode {
        mode: QueueMode,
    },
    /// Mark the current item unplayable on this device and move on.
    SkipUnavailable {
        key: QueueKey,
    },

    // -- saved queues -----------------------------------------------------
    RestoreSavedQueue {
        id: String,
    },
    PinSavedQueue {
        id: String,
        pinned: bool,
    },
    DeleteSavedQueue {
        id: String,
    },
    SaveQueueAsPlaylist {
        saved_queue_id: Option<String>,
        name: String,
    },
    SetSavedQueueCap {
        cap: u32,
    },

    // -- undo -------------------------------------------------------------
    Undo,
    Redo,
    /// Undo a specific entry from the history sheet.
    UndoEntry {
        id: String,
    },
    RestoreSelection,

    // -- library mutations (all through the outbox, all undoable) ---------
    SetRating {
        targets: Vec<RatingTarget>,
        rating: u32,
    },
    SetLoved {
        targets: Vec<RatingTarget>,
        loved: bool,
    },
    SetArtistLoved {
        artist_id: ArtistId,
        loved: bool,
    },
    CreatePlaylist {
        server_id: ServerId,
        name: String,
        track_ids: Vec<TrackId>,
    },
    DeletePlaylist {
        playlist_id: PlaylistId,
    },
    RenamePlaylist {
        playlist_id: PlaylistId,
        name: String,
        comment: Option<String>,
        public: Option<bool>,
    },
    PlaylistAdd {
        playlist_id: PlaylistId,
        track_ids: Vec<TrackId>,
        at_index: Option<u32>,
    },
    /// Indices into the playlist's current order.
    PlaylistRemove {
        playlist_id: PlaylistId,
        indices: Vec<u32>,
    },
    PlaylistMove {
        playlist_id: PlaylistId,
        from_index: u32,
        to_index: u32,
    },
    /// Marks a played track on the server (`scrobble submission=true`) — used only by the
    /// core's own scrobbler. The variant stays on the wire for API stability, but it is
    /// only acted on with the `sim` feature (it bypasses the threshold, session dedupe
    /// and the scrobble setting); a release core ignores it.
    Scrobble {
        track_id: TrackId,
        played_at: EpochMs,
        submission: bool,
    },

    // -- downloads --------------------------------------------------------
    Pin {
        target: PinTarget,
        transcode: bool,
    },
    Unpin {
        target: PinTarget,
    },
    ClearStreamCache,
    /// The album primer: the album page has been open a moment, or the
    /// pointer rests on its play button. The core resolves the album's
    /// first track and asks the device that owns playback (this one when
    /// nobody else does) to fetch its first seconds into the stream cache,
    /// so pressing play starts from disk. The owner decides with its own
    /// state: only on an unmetered network, not in battery saver, never on
    /// the coordinator; deduplicated and rate-limited. Fire and forget.
    PrimeAlbum {
        album_id: AlbumId,
    },
    /// [`Command::PrimeAlbum`] for one track (a hovered track row).
    PrimeTrack {
        track_id: TrackId,
    },
    /// What the platform's playback backend can do. `core_stream`: it reads
    /// `hocket-stream://<token>` media sources through the core's stream
    /// reader (`stream_open`/`stream_read`/`stream_close` on the core
    /// handle) instead of fetching URLs itself. Default false for an
    /// external backend (sources then carry the server URL as before); the
    /// native backend always reads through the core.
    SetBackendCapabilities {
        core_stream: bool,
    },
    SetStorageWarnThreshold {
        bytes: Option<f64>,
    },

    // -- jobs and problems ------------------------------------------------
    CancelJob {
        id: JobId,
    },
    RetryJob {
        id: JobId,
    },
    PauseJob {
        id: JobId,
    },
    ResumeJob {
        id: JobId,
    },
    RetryProblem {
        id: String,
    },
    DismissProblem {
        id: String,
    },
    DismissAllProblems,

    // -- filters and autoplay --------------------------------------------
    SaveFilter {
        filter: Filter,
    },
    DeleteFilter {
        id: FilterId,
    },
    /// Native API, behind the capability flag.
    CreateSmartPlaylist {
        server_id: ServerId,
        filter: Filter,
        name: String,
    },
    CreateStaticPlaylistFromFilter {
        server_id: ServerId,
        filter: Filter,
        name: String,
    },
    /// Writes the NSP document to `path` (or returns it via [`Event::NspExported`]).
    ExportNsp {
        filter: Filter,
        path: Option<String>,
    },
    SetAutoplaySettings {
        settings: AutoplaySettings,
    },

    // -- lyrics -----------------------------------------------------------
    SetLyricsOffset {
        track_id: TrackId,
        offset_ms: i32,
    },
    SetExternalLyricsEnabled {
        enabled: bool,
    },
    FetchLyrics {
        track_id: TrackId,
    },

    // -- settings ---------------------------------------------------------
    SetSetting {
        key: String,
        value: String,
    },
    ResetSetting {
        key: String,
    },
    SetSettingsSync {
        enabled: bool,
    },
    ExportConfig {
        include_secrets: bool,
    },
    /// Import a config document (`ExportConfig` output). Account-synced
    /// settings it changes are broadcast to the other devices like a local
    /// edit. Device-local settings (audio output, transcoding, storage,
    /// `connect.*`, display theme/accent, battery, …) describe the device the
    /// document came from and are left alone unless `include_device_local`
    /// is set (default false; older callers may omit it).
    ImportConfig {
        document: String,
        #[serde(default)]
        include_device_local: bool,
    },

    // -- audio ------------------------------------------------------------
    SetAudioSettings {
        settings: AudioSettings,
    },
    SetOutputDevice {
        id: Option<String>,
    },
    RefreshOutputDevices,

    // -- connect ----------------------------------------------------------
    SetCoordinatorUrl {
        url: Option<String>,
    },
    ConnectCoordinator,
    DisconnectCoordinator,
    SetLanDiscovery {
        enabled: bool,
    },
    /// Opens the picker: targets start pre-buffering.
    OpenHandoffPicker,
    CloseHandoffPicker,
    HandoffTo {
        device_id: DeviceId,
    },
    /// Accept the dormant resume offer and take transport here.
    ResumeHere,
    DismissResumeOffer,

    // -- sleep timer ------------------------------------------------------
    SetSleepTimer {
        timer: Option<SleepTimer>,
    },

    // -- from the platform ------------------------------------------------
    /// Reports from an external playback backend.
    BackendReport {
        report: BackendReport,
    },
    /// OS media session button/command (headset, lockscreen, MPRIS, SMTC).
    MediaSessionCommand {
        action: MediaSessionAction,
        value: Option<f64>,
    },
    /// Run a registry action against a target. The core validates applicability.
    RunAction {
        action_id: String,
        target: ActionTarget,
    },
    /// Custom shortcut binding (desktop). `shortcut` is a normalised chord string.
    SetShortcut {
        action_id: String,
        shortcut: Option<String>,
    },
    /// Choose-and-order customisation for a surface (`contextMenu`, `sidebar`, `mediaSession`).
    SetActionOrder {
        surface: String,
        action_ids: Vec<String>,
    },
    /// The UI's current multi-selection, so commands can snapshot it.
    SetSelection {
        target: ActionTarget,
    },
    /// Marks a saved queue / track as interacted with (for LRU).
    Touch {
        target: ActionTarget,
    },
}

impl Command {
    /// The variant name as it appears on the wire (`"addServer"`), for logs
    /// that must never carry the payload.
    pub fn kind(&self) -> String {
        serde_json::to_value(self)
            .ok()
            .and_then(|v| v.get("type").and_then(|t| t.as_str()).map(str::to_string))
            .unwrap_or_else(|| "?".into())
    }
}

// ---------------------------------------------------------------------------
// Queries (async request/response)
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct Page {
    pub offset: u32,
    pub limit: u32,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum Query {
    /// Everything a freshly attached UI needs, in one round trip.
    Snapshot,
    Servers,
    Tracks {
        server_id: ServerId,
        filter: Option<FilterNode>,
        sort: SortOrder,
        descending: bool,
        page: Page,
    },
    TrackCount {
        server_id: ServerId,
        filter: Option<FilterNode>,
    },
    Track {
        id: TrackId,
    },
    TracksByIds {
        ids: Vec<TrackId>,
    },
    Albums {
        server_id: ServerId,
        artist_id: Option<ArtistId>,
        genre: Option<String>,
        sort: SortOrder,
        descending: bool,
        page: Page,
    },
    AlbumCount {
        server_id: ServerId,
        artist_id: Option<ArtistId>,
        genre: Option<String>,
    },
    Album {
        id: AlbumId,
    },
    AlbumTracks {
        id: AlbumId,
    },
    Artists {
        server_id: ServerId,
        page: Page,
    },
    Artist {
        id: ArtistId,
    },
    ArtistTopSongs {
        id: ArtistId,
        count: u32,
    },
    Genres {
        server_id: ServerId,
    },
    Playlists {
        server_id: ServerId,
    },
    Playlist {
        id: PlaylistId,
    },
    PlaylistTracks {
        id: PlaylistId,
        page: Page,
    },
    /// Local-first; server results, when requested, arrive in a second [`Event::SearchResults`].
    Search {
        server_id: ServerId,
        query: String,
        limit: u32,
        include_server: bool,
        request_id: String,
    },
    Queue,
    SavedQueues,
    Lyrics {
        track_id: TrackId,
    },
    Related {
        track_id: TrackId,
        count: u32,
    },
    Stats {
        period_days: u32,
    },
    RecentlyPlayed {
        limit: u32,
    },
    Jobs,
    Problems,
    Pins,
    Storage,
    Filters,
    /// Evaluate a filter locally: matching count and server-expressibility.
    FilterPreview {
        filter: Filter,
    },
    Settings,
    Setting {
        key: String,
    },
    AudioSettings,
    OutputDevices,
    Connection,
    Devices,
    UndoState,
    /// Applicable actions for a target, ordered per the user's customisation of `surface`.
    Actions {
        surface: String,
        target: ActionTarget,
    },
    Shortcuts,
    /// Resolve artwork to a local file path at one of the fixed cache sizes (fetching if needed).
    Artwork {
        id: String,
        size: u32,
    },
    /// Direct stream/file URL for a track (what the backend would be given).
    MediaSource {
        track_id: TrackId,
    },
    /// Diagnostics bundle (crash logs, versions) as text for copy-to-clipboard.
    Diagnostics,
    /// Export a config document.
    ConfigDocument {
        include_secrets: bool,
    },
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct TrackPage {
    pub items: Vec<Track>,
    pub offset: u32,
    pub total: u32,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AlbumPage {
    pub items: Vec<Album>,
    pub offset: u32,
    pub total: u32,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ArtistPage {
    pub items: Vec<Artist>,
    pub offset: u32,
    pub total: u32,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SearchResults {
    pub request_id: String,
    pub query: String,
    pub tracks: Vec<TrackSummary>,
    pub albums: Vec<Album>,
    pub artists: Vec<Artist>,
    pub playlists: Vec<Playlist>,
    /// False for the local batch, true for the server batch appended below the divider.
    pub from_server: bool,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RelatedTrack {
    pub track: TrackSummary,
    pub provider: AutoplayProvider,
    pub score: Option<f64>,
    pub reason: String,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Shortcut {
    pub action_id: String,
    pub shortcut: Option<String>,
    pub default_shortcut: Option<String>,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FilterPreview {
    pub count: u32,
    pub capability: FilterCapability,
    pub sample: Vec<TrackSummary>,
}

/// Everything a UI needs on attach.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Snapshot {
    pub servers: Vec<ServerInfo>,
    pub session: Option<SessionDocument>,
    pub queue: QueueView,
    pub transport: TransportState,
    pub connection: ConnectionState,
    pub devices: Vec<DeviceInfo>,
    pub jobs: Vec<Job>,
    pub problems: Vec<Problem>,
    pub undo: UndoState,
    pub settings: Vec<Setting>,
    pub audio: AudioSettings,
    pub media_session: MediaSessionState,
    pub resume_offer: Option<ResumeOffer>,
    pub sleep_timer: Option<SleepTimer>,
    pub network: Option<NetworkState>,
    pub battery_saver: bool,
    pub sync_progress: Option<SyncProgress>,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum QueryResult {
    SnapshotResult(Snapshot),
    Servers(Vec<ServerInfo>),
    Tracks(TrackPage),
    Count(u32),
    TrackDetail(Option<Track>),
    TrackList(Vec<Track>),
    Albums(AlbumPage),
    AlbumDetail(Option<Album>),
    Artists(ArtistPage),
    ArtistDetail(Option<Artist>),
    Genres(Vec<Genre>),
    Playlists(Vec<Playlist>),
    PlaylistDetail(Option<Playlist>),
    Search(SearchResults),
    Queue(QueueView),
    SavedQueues(Vec<SavedQueue>),
    LyricsResult(Option<Lyrics>),
    Related(Vec<RelatedTrack>),
    Stats(ListeningStats),
    History(Vec<PlayHistoryEntry>),
    Jobs(Vec<Job>),
    Problems(Vec<Problem>),
    Pins(Vec<Pin>),
    Storage(StorageSummary),
    Filters(Vec<Filter>),
    Preview(FilterPreview),
    Settings(Vec<Setting>),
    SettingDetail(Option<Setting>),
    Audio(AudioSettings),
    OutputDevices(Vec<OutputDevice>),
    Connection(ConnectionState),
    Devices(Vec<DeviceInfo>),
    Undo(UndoState),
    Actions(Vec<ActionDescriptor>),
    Shortcuts(Vec<Shortcut>),
    /// Local file path.
    Path(Option<String>),
    Source(Option<MediaSource>),
    Text(String),
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SyncProgress {
    pub server_id: ServerId,
    pub phase: String,
    pub done: u32,
    pub total: Option<u32>,
    /// Tables that have completed and can be served locally.
    pub ready_tables: Vec<String>,
    pub finished: bool,
}

#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ErrorKind {
    Auth,
    Network,
    Server,
    Storage,
    Playback,
    Protocol,
    Internal,
}

/// What an `Event::PlayerNotice` is about, stable across releases and
/// languages (the `message` text is neither).
#[typeshare]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum PlayerNoticeCode {
    /// Offline: tracks neither downloaded nor fully cached are skipped.
    OfflineSkipping,
    /// Offline, and nothing left in the queue plays here: playback stopped.
    NothingAvailableOffline,
    /// No server connection to stream from.
    NoServer,
    /// A non-fatal playback problem (`detail`: the backend's message).
    PlaybackProblem,
    /// A track failed to play and was skipped (`detail`: its title).
    CouldNotPlaySkipped,
    /// Stopped after several unplayable tracks in a row (`detail`: the last title).
    CouldNotPlayStopped,
    /// Autoplay was asked for more and found nothing to add.
    AutoplayFoundNothing,
}

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", tag = "type", content = "data")]
pub enum Event {
    /// Emitted exactly once per core, when `Start` completes. Platforms key
    /// one-time work (credential replay, first-run setup) on this.
    Started {
        snapshot: Snapshot,
    },
    /// Emitted by `RequestSnapshot` (and by anything else that re-emits the
    /// whole state, such as `RemoveServer`) ahead of the `*Changed` replay.
    /// Same payload as `Started`, never confused with it.
    Snapshot {
        snapshot: Snapshot,
    },
    ServersChanged {
        servers: Vec<ServerInfo>,
    },
    SyncProgress {
        progress: SyncProgress,
    },
    /// Mirror tables changed; UIs should refetch visible queries. Empty = everything.
    LibraryChanged {
        server_id: ServerId,
        tables: Vec<String>,
        ids: Vec<String>,
    },
    SearchResults {
        results: SearchResults,
    },
    /// Ratings or loves changed: set here (including undo and the rating →
    /// love bridge) or, with `from_device`, on another signed-in device and
    /// relayed through Connect. The mirror already holds these values, so
    /// UIs patch every copy of the item they show (rows, detail headers,
    /// search results, menus) in place. Followed by a `LibraryChanged` for
    /// list refetches and, when the item is queued, by `NowPlayingChanged` /
    /// `QueueChanged` / `MediaSession`. A library sync that picks up changes
    /// made elsewhere reports them with `LibraryChanged` only.
    LibraryItemsChanged {
        server_id: ServerId,
        items: Vec<LibraryItemState>,
        /// The device the change came from; `None` for this one.
        #[serde(default)]
        from_device: Option<DeviceId>,
    },
    /// A playlist changed (tracks added, removed or moved, renamed, created
    /// or deleted), here or, with `from_device`, on another signed-in device.
    /// `playlist` is the mirror's row now; `None` when it was deleted.
    /// Screens showing it (its detail page, playlist lists and pickers)
    /// refetch its tracks. Followed by a `LibraryChanged`.
    PlaylistChanged {
        server_id: ServerId,
        playlist_id: PlaylistId,
        playlist: Option<Playlist>,
        #[serde(default)]
        from_device: Option<DeviceId>,
    },

    SessionChanged {
        document: SessionDocument,
    },
    QueueChanged {
        queue: QueueView,
    },
    TransportChanged {
        transport: TransportState,
    },
    /// The item now playing (or `None` when stopped), with a resolved track.
    NowPlayingChanged {
        entry: Option<QueueEntry>,
    },
    SavedQueuesChanged {
        queues: Vec<SavedQueue>,
    },
    UndoChanged {
        state: UndoState,
    },
    Toast {
        toast: Toast,
    },
    /// Inline player-bar line for a non-fatal playback issue ("Couldn't play X, skipped").
    /// `message` is the core's English text; platforms that show their own
    /// (localised) text match on `code` and fill in `detail`. All `None`
    /// clears the line.
    PlayerNotice {
        message: Option<String>,
        #[serde(default)]
        code: Option<PlayerNoticeCode>,
        /// The variable part of the notice: the track's title for
        /// `couldNotPlaySkipped` / `couldNotPlayStopped`, the backend's
        /// message for `playbackProblem`; `None` for the others.
        #[serde(default)]
        detail: Option<String>,
    },

    JobsChanged {
        jobs: Vec<Job>,
    },
    ProblemsChanged {
        problems: Vec<Problem>,
    },

    ConnectionChanged {
        state: ConnectionState,
    },
    /// The network the platform last reported with `SetNetworkState`
    /// (`Snapshot.network`): emitted whenever it changes and in every
    /// replay. `None` until the platform first reports one.
    NetworkChanged {
        network: Option<NetworkState>,
    },
    DevicesChanged {
        devices: Vec<DeviceInfo>,
    },
    HandoffPickerChanged {
        open: bool,
        targets: Vec<DeviceInfo>,
    },
    ResumeOfferChanged {
        offer: Option<ResumeOffer>,
    },

    LyricsChanged {
        track_id: TrackId,
        lyrics: Option<Lyrics>,
    },
    PinsChanged {
        pins: Vec<Pin>,
    },
    StorageChanged {
        storage: StorageSummary,
    },
    FiltersChanged {
        filters: Vec<Filter>,
    },
    SettingChanged {
        setting: Setting,
    },
    AudioSettingsChanged {
        settings: AudioSettings,
    },
    OutputDevicesChanged {
        devices: Vec<OutputDevice>,
    },
    SleepTimerChanged {
        timer: Option<SleepTimer>,
    },
    ShortcutsChanged {
        shortcuts: Vec<Shortcut>,
    },
    ActionsChanged {
        surface: String,
    },
    NspExported {
        filter_id: FilterId,
        document: String,
        path: Option<String>,
    },
    ConfigExported {
        document: String,
    },

    /// Drive an external backend (Android). Not emitted in native mode.
    Backend {
        command: BackendCommand,
    },
    /// Drive the OS media session (both platforms).
    MediaSession {
        state: MediaSessionState,
    },

    Error {
        kind: ErrorKind,
        message: String,
        detail: Option<String>,
    },
    Log {
        level: String,
        target: String,
        message: String,
    },
}

// ---------------------------------------------------------------------------
// Config backup document
// ---------------------------------------------------------------------------

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ConfigDocument {
    pub version: u32,
    pub exported_at: EpochMs,
    pub settings: Vec<Setting>,
    pub filters: Vec<Filter>,
    pub shortcuts: Vec<Shortcut>,
    pub servers: Vec<ServerInfo>,
    /// Only present when exported with secrets; encrypted at rest by the platform keystore otherwise.
    pub secrets: Option<HashMap<String, String>>,
    pub audio: AudioSettings,
    pub autoplay: AutoplaySettings,
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extra: HashMap<String, String>,
}

#[cfg(test)]
mod redaction_tests {
    use super::*;

    #[test]
    fn command_debug_never_shows_the_password_and_kind_is_the_wire_tag() {
        let cmd = Command::AddServer {
            url: "https://music.example/".into(),
            username: "alice".into(),
            password: "hunter2".into(),
            name: None,
        };
        let dbg = format!("{cmd:?}");
        assert!(!dbg.contains("hunter2"), "{dbg}");
        assert!(dbg.contains("<redacted>"), "{dbg}");
        assert_eq!(cmd.kind(), "addServer");
        assert_eq!(Command::Start.kind(), "start");
        // The wire shape is unchanged: a plain string.
        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains(r#""password":"hunter2""#), "{json}");
        let back: Command = serde_json::from_str(&json).unwrap();
        assert_eq!(back, cmd);
    }

    #[test]
    fn media_source_debug_strips_the_query_string() {
        let source = MediaSource {
            key: "k1".into(),
            track: TrackSummary::default(),
            url: "https://music.example/rest/stream?id=t0&u=alice&t=abc123&s=salt".into(),
            headers: [("Authorization".to_string(), "Bearer xyz".to_string())].into(),
            mime_type: None,
            gain_db: 0.0,
            transcoded: false,
        };
        let dbg = format!("{source:?}");
        assert!(dbg.contains("https://music.example/rest/stream"), "{dbg}");
        assert!(
            !dbg.contains("abc123") && !dbg.contains("salt") && !dbg.contains("xyz"),
            "{dbg}"
        );
        let cmd = BackendCommand::Load {
            source,
            next: None,
            position_ms: 0,
            play: true,
        };
        assert!(!format!("{cmd:?}").contains("abc123"));
        assert_eq!(redact_url("file:///tmp/a.flac"), "file:///tmp/a.flac");
        assert_eq!(redact_url("https://h/p#frag"), "https://h/p");
    }
}
