// Generates src/renderer/components/material-icons.ts: the Material Symbols
// (rounded) glyphs the renderer uses, as SVG path bodies, from the Iconify
// dataset (@iconify-json/material-symbols, Apache-2.0). Only the icons listed
// here are emitted, so the app doesn't ship the whole set.
//
//   node scripts/gen-icons.mjs
//
// Each renderer name maps to a Material Symbols name; for each we emit the
// outlined and the filled rounded variant (the same glyph when the symbol has
// only one). Re-run after changing the list; the output is committed.
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const set = require("@iconify-json/material-symbols/icons.json");

/** Renderer name → Material Symbols name (underscores or dashes). */
const MAP = {
  play: "play_arrow", pause: "pause", stop: "stop", next: "skip_next", previous: "skip_previous", rewind: "fast_rewind", forward: "fast_forward",
  shuffle: "shuffle", repeat: "repeat", repeatOne: "repeat_one", autoplay: "all_inclusive", volume: "volume_up", mute: "volume_off",
  heart: "favorite", heartOff: "heart_minus", star: "star", starOff: "star",
  queue: "queue_music", lyrics: "lyrics", fullscreen: "fullscreen", mini: "picture_in_picture_alt", devices: "devices",
  search: "search", command: "keyboard_command_key", settings: "settings",
  home: "home", library: "library_music", album: "album", artist: "person", playlist: "playlist_play", playlistAdd: "playlist_add", song: "music_note", genre: "category",
  download: "download", downloadOff: "file_download_off", cached: "hard_drive", filter: "filter_alt", filterAdd: "library_add", stats: "insights", info: "info",
  remove: "remove", trash: "delete", edit: "edit", close: "close", check: "check",
  chevronDown: "expand_more", chevronRight: "chevron_right", chevronLeft: "chevron_left", chevronUp: "expand_less",
  arrowDown: "arrow_downward", arrowUp: "arrow_upward", back: "arrow_back", forwardArrow: "arrow_forward", undo: "undo", redo: "redo",
  playNext: "queue_play_next", playLater: "add_to_queue", pin: "push_pin", pinOff: "keep_off", restore: "history", seek: "arrow_forward", sleep: "bedtime", bug: "bug_report",
  selectAll: "select_all", grip: "drag_indicator", dragHandle: "drag_handle", more: "more_horiz", moreVert: "more_vert", minimize: "minimize", maximize: "crop_square", restoreWin: "filter_none",
  spinner: "progress_activity", offline: "wifi_off", warn: "warning", battery: "battery_saver", external: "open_in_new", folder: "folder",
  copy: "content_copy", resume: "play_circle", music: "music_note", cloud: "cloud", lan: "lan", plus: "add",
};

function body(name) {
  let n = name;
  for (let i = 0; i < 8; i++) {
    const icon = set.icons[n];
    if (icon) return icon.body;
    const alias = set.aliases?.[n];
    if (!alias) return undefined;
    n = alias.parent;
  }
  return undefined;
}

const first = (...names) => {
  for (const n of names) {
    const b = body(n);
    if (b) return b;
  }
  return undefined;
};

const out = {};
const missing = [];
for (const [local, material] of Object.entries(MAP)) {
  const m = material.replace(/_/g, "-");
  const filled = first(`${m}-rounded`, m);
  const outline = first(`${m}-outline-rounded`, `${m}-rounded`, `${m}-outline`, m);
  if (!filled || !outline) missing.push(`${local} → ${material}`);
  else out[local] = outline === filled ? [outline] : [outline, filled];
}
if (missing.length) {
  console.error(`missing Material Symbols: ${missing.join(", ")}`);
  process.exit(1);
}

const target = fileURLToPath(new URL("../src/renderer/components/material-icons.ts", import.meta.url));
const lines = Object.entries(out).map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`);
writeFileSync(target, `// Generated by scripts/gen-icons.mjs from @iconify-json/material-symbols
// (Material Symbols, Apache-2.0, rounded). Do not edit; edit the script's map.
// Each entry: [outlined, filled?] SVG bodies for a 24×24 viewBox.
export const MATERIAL_ICONS: Record<string, readonly [string, string?]> = {
${lines.join("\n")}
};
`);
console.log(`[gen-icons] ${Object.keys(out).length} icons → ${target}`);
