// Loads the native napi addon (crates/hocket-node) or falls back to FakeCore.
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { Command, CoreConfig, Event, Query, QueryResult } from "@core/api";
import type { CoreHandle } from "@shared/core-handle";
import { API_SCHEMA_VERSION } from "@shared/constants";
import { FakeCore } from "./fake-core";

/** Shape of `native/index.js` as generated by `napi build --platform`. */
export interface NativeModule {
  HocketCore: new (configJson: string) => {
    setListener(cb: (json: string) => void): void;
    dispatch(json: string): void;
    query(json: string): Promise<string>;
  };
  MediaSession: new (options: { name: string; desktopEntry?: string; hwnd?: number; trackIdPrefix?: string }, cb: (json: string) => void) => {
    setState(json: string): void;
    setPosition(positionMs: number): void;
    detach(): void;
    isAttached(): boolean;
  };
  initLogging(level: string): void;
  coreVersion(): string;
  apiSchemaVersion(): number;
  mediaSessionAvailable(): boolean;
}

export interface LoadedNative {
  module: NativeModule;
  path: string;
}

/** Candidate addon locations: packaged resources first, then the dev tree. */
export function nativeCandidates(appRoot: string): string[] {
  const out: string[] = [];
  if (process.resourcesPath) out.push(join(process.resourcesPath, "native", "index.js"));
  out.push(join(appRoot, "native", "index.js"));
  return out;
}

export function loadNative(appRoot: string): LoadedNative | undefined {
  for (const path of nativeCandidates(appRoot)) {
    if (!existsSync(path)) continue;
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const mod = require(path) as NativeModule;
      const schema = mod.apiSchemaVersion?.();
      if (schema !== API_SCHEMA_VERSION) {
        console.error(`[core] addon at ${path} has API schema ${schema}, app expects ${API_SCHEMA_VERSION}; ignoring it`);
        continue;
      }
      return { module: mod, path };
    } catch (err) {
      console.error(`[core] failed to load addon at ${path}:`, err);
    }
  }
  return undefined;
}

class NativeCoreHandle implements CoreHandle {
  readonly kind = "native" as const;
  private listeners = new Set<(e: Event) => void>();
  private core: InstanceType<NativeModule["HocketCore"]>;

  constructor(mod: NativeModule, config: CoreConfig) {
    this.core = new mod.HocketCore(JSON.stringify(config));
    this.core.setListener((json) => {
      let event: Event;
      try {
        event = JSON.parse(json) as Event;
      } catch (err) {
        console.error("[core] unparseable event", err, json.slice(0, 200));
        return;
      }
      for (const l of this.listeners) {
        try {
          l(event);
        } catch (err) {
          console.error("[core] listener threw", err);
        }
      }
    });
  }

  dispatch(command: Command): void {
    this.core.dispatch(JSON.stringify(command));
  }

  async query(query: Query): Promise<QueryResult> {
    return JSON.parse(await this.core.query(JSON.stringify(query))) as QueryResult;
  }

  onEvent(listener: (e: Event) => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  async shutdown(): Promise<void> {
    this.core.dispatch(JSON.stringify({ type: "shutdown" } satisfies Command));
  }
}

export interface CreateCoreOptions {
  appRoot: string;
  forceFake: boolean;
  fakeTimeScale?: number;
}

export function createCore(config: CoreConfig, opts: CreateCoreOptions): { core: CoreHandle; native?: LoadedNative } {
  if (!opts.forceFake) {
    const native = loadNative(opts.appRoot);
    if (native) {
      native.module.initLogging(process.env.HOCKET_LOG ?? "info");
      console.log(`[core] native addon ${native.module.coreVersion()} from ${native.path}`);
      return { core: new NativeCoreHandle(native.module, config), native };
    }
    console.warn("[core] native addon not found; using the fake core (run `pnpm gen` to build it)");
  }
  return { core: new FakeCore(config, { timeScale: opts.fakeTimeScale ?? 1 }) };
}
