-- Hocket local database schema. THIS FILE IS THE SCHEMA CONTRACT between
-- core-server (db/, subsonic/, outbox/, jobs/, downloads/, cache/) and
-- core-library (filters/, lyrics/, autoplay/, settings/, stats/).
--
-- It is applied verbatim as migration 0001. Later migrations are additive and
-- live in db/migrations/NNNN_*.sql; this file is kept accurate by hand so a
-- reader sees the *current* shape in one place (schema_version records what
-- was actually applied).
--
-- Conventions:
--   * Every entity table carries server_id (multi-server framework, one server for now).
--   * Column names on `tracks` are exactly the snake_case names of api::Track's
--     fields (nested ReplayGain / SonicAttributes are flattened with the
--     prefixes shown). Filter SQL generated by the filters module targets these
--     names directly, e.g. `tracks.rating >= ?`.
--   * Booleans are INTEGER 0/1. Epoch timestamps are REAL milliseconds
--     (api::EpochMs). Durations are INTEGER milliseconds.
--   * JSON blob columns are TEXT.
--   * Mirror tables (tracks, albums, artists, genres, playlists, playlist_tracks,
--     capabilities, image_cache, lyrics_cache, cache_entries) are a cache and
--     may be dropped and rebuilt. Non-rebuildable tables (servers, pins,
--     pin_tracks, outbox, jobs, job_items, problems, play_history, saved_state,
--     settings, filters) get a file backup before any migration runs.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS schema_version (
    version     INTEGER NOT NULL,
    applied_at  REAL    NOT NULL
);

-- ---------------------------------------------------------------------------
-- Servers and capabilities
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS servers (
    id            TEXT PRIMARY KEY,
    url           TEXT NOT NULL,
    username      TEXT NOT NULL,
    name          TEXT NOT NULL,
    last_sync     REAL,
    -- api::ServerCapabilities as JSON (also mirrored row-wise in `capabilities`).
    capabilities  TEXT NOT NULL DEFAULT '{}',
    created_at    REAL NOT NULL
);

-- One row per (server, capability name) so filters can ask "does this server
-- support X" without parsing JSON. Rebuilt on every probe.
CREATE TABLE IF NOT EXISTS capabilities (
    server_id  TEXT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    enabled    INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (server_id, name)
);

-- ---------------------------------------------------------------------------
-- Library mirror
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tracks (
    id                TEXT NOT NULL,
    server_id         TEXT NOT NULL,
    title             TEXT NOT NULL,
    album_id          TEXT,
    album             TEXT,
    artist_id         TEXT,
    artist            TEXT,
    album_artist      TEXT,
    track_number      INTEGER,
    disc_number       INTEGER,
    year              INTEGER,
    genre             TEXT,
    duration_ms       INTEGER NOT NULL DEFAULT 0,
    bit_rate          INTEGER,
    sample_rate       INTEGER,
    bit_depth         INTEGER,
    channels          INTEGER,
    suffix            TEXT,
    content_type      TEXT,
    size_bytes        REAL,
    path              TEXT,
    cover_art         TEXT,
    rating            INTEGER NOT NULL DEFAULT 0,
    loved             INTEGER NOT NULL DEFAULT 0,
    play_count        INTEGER NOT NULL DEFAULT 0,
    last_played       REAL,
    created           REAL,
    -- server-reported modification time (OpenSubsonic `changed`/`updated`), used by incremental sync
    changed           REAL,
    rg_track_gain     REAL,
    rg_track_peak     REAL,
    rg_album_gain     REAL,
    rg_album_peak     REAL,
    bpm               REAL,
    key               TEXT,
    energy            REAL,
    mood              TEXT,
    danceability      REAL,
    valence           REAL,
    -- api::OfflineState: 0 none, 1 cached, 2 downloaded, 3 downloading
    offline           INTEGER NOT NULL DEFAULT 0,
    music_brainz_id   TEXT,
    explicit          INTEGER NOT NULL DEFAULT 0,
    comment           TEXT,
    has_lyrics        INTEGER NOT NULL DEFAULT 0,
    -- local (this device) listening data, maintained by the scrobbler
    local_play_count  INTEGER NOT NULL DEFAULT 0,
    local_last_played REAL,
    -- denormalised from albums.is_compilation
    is_compilation    INTEGER NOT NULL DEFAULT 0,
    -- sync bookkeeping: generation of the last sync that saw this row (mark-and-sweep)
    sync_gen          INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (server_id, id)
);
CREATE INDEX IF NOT EXISTS idx_tracks_album    ON tracks(server_id, album_id, disc_number, track_number);
CREATE INDEX IF NOT EXISTS idx_tracks_artist   ON tracks(server_id, artist_id);
CREATE INDEX IF NOT EXISTS idx_tracks_title    ON tracks(server_id, title COLLATE NOCASE);
CREATE INDEX IF NOT EXISTS idx_tracks_genre    ON tracks(server_id, genre);
CREATE INDEX IF NOT EXISTS idx_tracks_created  ON tracks(server_id, created);
CREATE INDEX IF NOT EXISTS idx_tracks_rating   ON tracks(server_id, rating);
CREATE INDEX IF NOT EXISTS idx_tracks_offline  ON tracks(server_id, offline);
CREATE INDEX IF NOT EXISTS idx_tracks_gen      ON tracks(server_id, sync_gen);

-- Full-text search over title/album/artist with prefix matching. External
-- content table kept in step by triggers.
CREATE VIRTUAL TABLE IF NOT EXISTS tracks_fts USING fts5(
    title, album, artist,
    content='tracks', content_rowid='rowid',
    tokenize='unicode61 remove_diacritics 2',
    prefix='2 3 4'
);
CREATE TRIGGER IF NOT EXISTS tracks_ai AFTER INSERT ON tracks BEGIN
    INSERT INTO tracks_fts(rowid, title, album, artist) VALUES (new.rowid, new.title, new.album, new.artist);
END;
CREATE TRIGGER IF NOT EXISTS tracks_ad AFTER DELETE ON tracks BEGIN
    INSERT INTO tracks_fts(tracks_fts, rowid, title, album, artist) VALUES ('delete', old.rowid, old.title, old.album, old.artist);
END;
CREATE TRIGGER IF NOT EXISTS tracks_au AFTER UPDATE OF title, album, artist ON tracks BEGIN
    INSERT INTO tracks_fts(tracks_fts, rowid, title, album, artist) VALUES ('delete', old.rowid, old.title, old.album, old.artist);
    INSERT INTO tracks_fts(rowid, title, album, artist) VALUES (new.rowid, new.title, new.album, new.artist);
END;

CREATE TABLE IF NOT EXISTS albums (
    id               TEXT NOT NULL,
    server_id        TEXT NOT NULL,
    name             TEXT NOT NULL,
    artist_id        TEXT,
    artist           TEXT,
    year             INTEGER,
    genre            TEXT,
    song_count       INTEGER NOT NULL DEFAULT 0,
    duration_ms      INTEGER NOT NULL DEFAULT 0,
    cover_art        TEXT,
    rating           INTEGER NOT NULL DEFAULT 0,
    loved            INTEGER NOT NULL DEFAULT 0,
    play_count       INTEGER NOT NULL DEFAULT 0,
    created          REAL,
    changed          REAL,
    last_played      REAL,
    is_compilation   INTEGER NOT NULL DEFAULT 0,
    music_brainz_id  TEXT,
    rg_album_gain    REAL,
    rg_album_peak    REAL,
    -- api::OfflineState derived from pins
    offline          INTEGER NOT NULL DEFAULT 0,
    sync_gen         INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (server_id, id)
);
CREATE INDEX IF NOT EXISTS idx_albums_artist ON albums(server_id, artist_id);
CREATE INDEX IF NOT EXISTS idx_albums_name   ON albums(server_id, name COLLATE NOCASE);
CREATE INDEX IF NOT EXISTS idx_albums_genre  ON albums(server_id, genre);
CREATE INDEX IF NOT EXISTS idx_albums_gen    ON albums(server_id, sync_gen);

CREATE VIRTUAL TABLE IF NOT EXISTS albums_fts USING fts5(
    name, artist,
    content='albums', content_rowid='rowid',
    tokenize='unicode61 remove_diacritics 2',
    prefix='2 3 4'
);
CREATE TRIGGER IF NOT EXISTS albums_ai AFTER INSERT ON albums BEGIN
    INSERT INTO albums_fts(rowid, name, artist) VALUES (new.rowid, new.name, new.artist);
END;
CREATE TRIGGER IF NOT EXISTS albums_ad AFTER DELETE ON albums BEGIN
    INSERT INTO albums_fts(albums_fts, rowid, name, artist) VALUES ('delete', old.rowid, old.name, old.artist);
END;
CREATE TRIGGER IF NOT EXISTS albums_au AFTER UPDATE OF name, artist ON albums BEGIN
    INSERT INTO albums_fts(albums_fts, rowid, name, artist) VALUES ('delete', old.rowid, old.name, old.artist);
    INSERT INTO albums_fts(rowid, name, artist) VALUES (new.rowid, new.name, new.artist);
END;

CREATE TABLE IF NOT EXISTS artists (
    id                TEXT NOT NULL,
    server_id         TEXT NOT NULL,
    name              TEXT NOT NULL,
    album_count       INTEGER NOT NULL DEFAULT 0,
    song_count        INTEGER NOT NULL DEFAULT 0,
    cover_art         TEXT,
    artist_image_url  TEXT,
    loved             INTEGER NOT NULL DEFAULT 0,
    music_brainz_id   TEXT,
    biography         TEXT,
    sync_gen          INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (server_id, id)
);
CREATE INDEX IF NOT EXISTS idx_artists_name ON artists(server_id, name COLLATE NOCASE);
CREATE INDEX IF NOT EXISTS idx_artists_gen  ON artists(server_id, sync_gen);

CREATE VIRTUAL TABLE IF NOT EXISTS artists_fts USING fts5(
    name,
    content='artists', content_rowid='rowid',
    tokenize='unicode61 remove_diacritics 2',
    prefix='2 3 4'
);
CREATE TRIGGER IF NOT EXISTS artists_ai AFTER INSERT ON artists BEGIN
    INSERT INTO artists_fts(rowid, name) VALUES (new.rowid, new.name);
END;
CREATE TRIGGER IF NOT EXISTS artists_ad AFTER DELETE ON artists BEGIN
    INSERT INTO artists_fts(artists_fts, rowid, name) VALUES ('delete', old.rowid, old.name);
END;
CREATE TRIGGER IF NOT EXISTS artists_au AFTER UPDATE OF name ON artists BEGIN
    INSERT INTO artists_fts(artists_fts, rowid, name) VALUES ('delete', old.rowid, old.name);
    INSERT INTO artists_fts(rowid, name) VALUES (new.rowid, new.name);
END;

CREATE TABLE IF NOT EXISTS genres (
    server_id    TEXT NOT NULL,
    name         TEXT NOT NULL,
    song_count   INTEGER NOT NULL DEFAULT 0,
    album_count  INTEGER NOT NULL DEFAULT 0,
    sync_gen     INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (server_id, name)
);

CREATE TABLE IF NOT EXISTS playlists (
    id           TEXT NOT NULL,
    server_id    TEXT NOT NULL,
    name         TEXT NOT NULL,
    comment      TEXT,
    owner        TEXT,
    public       INTEGER NOT NULL DEFAULT 0,
    song_count   INTEGER NOT NULL DEFAULT 0,
    duration_ms  INTEGER NOT NULL DEFAULT 0,
    cover_art    TEXT,
    created      REAL,
    changed      REAL,
    is_smart     INTEGER NOT NULL DEFAULT 0,
    is_mine      INTEGER NOT NULL DEFAULT 0,
    -- native-API smart playlist rules as JSON (NULL when not smart / not readable)
    rules        TEXT,
    offline      INTEGER NOT NULL DEFAULT 0,
    -- whether playlist_tracks has been populated for this playlist
    tracks_synced INTEGER NOT NULL DEFAULT 0,
    sync_gen     INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (server_id, id)
);

CREATE TABLE IF NOT EXISTS playlist_tracks (
    server_id    TEXT NOT NULL,
    playlist_id  TEXT NOT NULL,
    position     INTEGER NOT NULL,
    track_id     TEXT NOT NULL,
    PRIMARY KEY (server_id, playlist_id, position)
);
CREATE INDEX IF NOT EXISTS idx_playlist_tracks_track ON playlist_tracks(server_id, track_id);

-- ---------------------------------------------------------------------------
-- Local listening data (not rebuildable)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS play_history (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    server_id   TEXT NOT NULL,
    track_id    TEXT NOT NULL,
    played_at   REAL NOT NULL,
    played_ms   INTEGER NOT NULL DEFAULT 0,
    scrobbled   INTEGER NOT NULL DEFAULT 0,
    device_id   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_play_history_at    ON play_history(played_at);
CREATE INDEX IF NOT EXISTS idx_play_history_track ON play_history(server_id, track_id);

-- ---------------------------------------------------------------------------
-- Outbox (durable pending mutations; not rebuildable)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS outbox (
    id               TEXT PRIMARY KEY,
    server_id        TEXT NOT NULL,
    -- outbox::Mutation as JSON
    mutation         TEXT NOT NULL,
    -- 'pending' | 'inflight' | 'done' | 'failed' | 'cancelled'
    status           TEXT NOT NULL DEFAULT 'pending',
    created_at       REAL NOT NULL,
    attempts         INTEGER NOT NULL DEFAULT 0,
    next_attempt_at  REAL NOT NULL DEFAULT 0,
    last_error       TEXT,
    -- for coalescing/undo: the entity this mutation targets ("track:<id>", "playlist:<id>")
    target           TEXT,
    -- prior server value snapshot (JSON) for conflict detection / CAS
    expected_prior   TEXT,
    finished_at      REAL
);
CREATE INDEX IF NOT EXISTS idx_outbox_status ON outbox(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_outbox_target ON outbox(target);

-- ---------------------------------------------------------------------------
-- Jobs and problems (not rebuildable)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS jobs (
    id           TEXT PRIMARY KEY,
    -- api::JobKind camelCase name
    kind         TEXT NOT NULL,
    label        TEXT NOT NULL,
    -- api::JobState camelCase name
    state        TEXT NOT NULL,
    -- opaque per-kind payload JSON (what to do)
    payload      TEXT NOT NULL DEFAULT '{}',
    done         INTEGER NOT NULL DEFAULT 0,
    total        INTEGER,
    failed       INTEGER NOT NULL DEFAULT 0,
    created_at   REAL NOT NULL,
    updated_at   REAL NOT NULL,
    cancellable  INTEGER NOT NULL DEFAULT 1,
    -- cursor JSON for resumable jobs (e.g. sync offset)
    cursor       TEXT
);
CREATE INDEX IF NOT EXISTS idx_jobs_state ON jobs(state, created_at);

CREATE TABLE IF NOT EXISTS job_items (
    job_id     TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    seq        INTEGER NOT NULL,
    -- item payload JSON (e.g. a track id)
    item       TEXT NOT NULL,
    -- 'pending' | 'done' | 'failed' | 'cancelled'
    state      TEXT NOT NULL DEFAULT 'pending',
    attempts   INTEGER NOT NULL DEFAULT 0,
    error      TEXT,
    PRIMARY KEY (job_id, seq)
);
CREATE INDEX IF NOT EXISTS idx_job_items_state ON job_items(job_id, state);

CREATE TABLE IF NOT EXISTS problems (
    id          TEXT PRIMARY KEY,
    job_id      TEXT,
    summary     TEXT NOT NULL,
    detail      TEXT,
    created_at  REAL NOT NULL,
    retryable   INTEGER NOT NULL DEFAULT 0,
    -- retry action payload JSON (interpreted by the job queue)
    retry       TEXT,
    dismissed   INTEGER NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Downloads (pins; not rebuildable) and the evictable stream cache
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pins (
    server_id         TEXT NOT NULL,
    -- 'track' | 'album' | 'playlist'
    target_kind       TEXT NOT NULL,
    target_id         TEXT NOT NULL,
    label             TEXT NOT NULL,
    cover_art         TEXT,
    created_at        REAL NOT NULL,
    transcoded        INTEGER NOT NULL DEFAULT 0,
    -- transcoding profile JSON used when transcoded=1
    profile           TEXT,
    PRIMARY KEY (server_id, target_kind, target_id)
);

-- Materialised membership: which tracks each pin wants, and their file state.
CREATE TABLE IF NOT EXISTS pin_tracks (
    server_id     TEXT NOT NULL,
    target_kind   TEXT NOT NULL,
    target_id     TEXT NOT NULL,
    track_id      TEXT NOT NULL,
    -- 'wanted' | 'downloading' | 'done' | 'failed'
    state         TEXT NOT NULL DEFAULT 'wanted',
    path          TEXT,
    bytes         REAL NOT NULL DEFAULT 0,
    suffix        TEXT,
    content_type  TEXT,
    -- gain in dB computed/stored at download time (transcodes drop tags)
    gain_db       REAL,
    peak          REAL,
    downloaded_at REAL,
    error         TEXT,
    PRIMARY KEY (server_id, target_kind, target_id, track_id)
);
CREATE INDEX IF NOT EXISTS idx_pin_tracks_track ON pin_tracks(server_id, track_id);
CREATE INDEX IF NOT EXISTS idx_pin_tracks_state ON pin_tracks(state);

-- Evictable stream cache index (rebuildable from the directory).
CREATE TABLE IF NOT EXISTS cache_entries (
    server_id     TEXT NOT NULL,
    track_id      TEXT NOT NULL,
    path          TEXT NOT NULL,
    bytes         REAL NOT NULL DEFAULT 0,
    content_type  TEXT,
    -- transcoding profile JSON the entry was fetched with ('' for original)
    profile       TEXT NOT NULL DEFAULT '',
    created_at    REAL NOT NULL,
    last_used_at  REAL NOT NULL,
    complete      INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (server_id, track_id, profile)
);
CREATE INDEX IF NOT EXISTS idx_cache_entries_lru ON cache_entries(last_used_at);

-- ---------------------------------------------------------------------------
-- Metadata caches (rebuildable)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lyrics_cache (
    server_id    TEXT NOT NULL,
    track_id     TEXT NOT NULL,
    -- 'server' | 'external' | 'embedded'
    source       TEXT NOT NULL,
    -- api::Lyrics JSON, or '' when the lookup produced nothing (negative cache)
    json         TEXT NOT NULL,
    fetched_at   REAL NOT NULL,
    last_used_at REAL NOT NULL,
    bytes        INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (server_id, track_id, source)
);

CREATE TABLE IF NOT EXISTS image_cache (
    server_id     TEXT NOT NULL,
    -- cover art / artist image id as given to getCoverArt
    image_id      TEXT NOT NULL,
    -- one of 64, 160, 320, 640, 1280
    size          INTEGER NOT NULL,
    path          TEXT NOT NULL,
    bytes         REAL NOT NULL DEFAULT 0,
    content_type  TEXT,
    fetched_at    REAL NOT NULL,
    last_used_at  REAL NOT NULL,
    PRIMARY KEY (server_id, image_id, size)
);
CREATE INDEX IF NOT EXISTS idx_image_cache_lru ON image_cache(last_used_at);

-- Generic small metadata cache (artist info, similar songs, top songs, ...).
CREATE TABLE IF NOT EXISTS metadata_cache (
    server_id    TEXT NOT NULL,
    -- namespaced key, e.g. "artistInfo2:<id>", "similarSongs2:<id>:50"
    key          TEXT NOT NULL,
    json         TEXT NOT NULL,
    fetched_at   REAL NOT NULL,
    expires_at   REAL NOT NULL,
    bytes        INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (server_id, key)
);

-- ---------------------------------------------------------------------------
-- Settings, filters, saved state (not rebuildable)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS settings (
    key         TEXT PRIMARY KEY,
    -- JSON-encoded value (api::Setting.value)
    value       TEXT NOT NULL,
    -- 'deviceLocal' | 'accountSynced'
    scope       TEXT NOT NULL,
    updated_at  REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS filters (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    -- api::Filter as JSON
    json        TEXT NOT NULL,
    created_at  REAL NOT NULL,
    updated_at  REAL NOT NULL
);

-- Arbitrary JSON documents keyed by name: the session document ("session"),
-- saved queues ("savedQueues"), shortcuts ("shortcuts"), action orders
-- ("actionOrder:<surface>"), sync cursors ("sync:<serverId>"), lyrics offsets
-- ("lyricsOffset:<trackId>"), autoplay settings, ...
CREATE TABLE IF NOT EXISTS saved_state (
    key         TEXT PRIMARY KEY,
    json        TEXT NOT NULL,
    updated_at  REAL NOT NULL
);
