// Every user-visible string, keyed by id, from the first commit (design.md
// "Strings externalised from the first commit"). `t(id, params)` substitutes
// `{name}` placeholders. Ids are grouped by surface.
const STRINGS = {
  "app.name": "Hocket",
  "app.devBanner": "Development build: running against the fake core (no native addon loaded).",
  "app.loading": "Starting…",

  // Navigation
  "nav.home": "Home",
  "nav.albums": "Albums",
  "nav.artists": "Artists",
  "nav.playlists": "Playlists",
  "nav.songs": "Songs",
  "nav.genres": "Genres",
  "nav.downloads": "Downloads",
  "nav.filters": "Filters",
  "nav.stats": "Stats",
  "nav.settings": "Settings",
  "nav.library": "Library",
  "nav.savedFilters": "Saved filters",
  "nav.playlistsSection": "Playlists",
  "nav.customise": "Customise sidebar…",

  // Server setup
  "setup.title": "Connect to your Navidrome server",
  "setup.subtitle": "Navidrome 0.63.0 or newer. Your password stays on this device, encrypted by the operating system.",
  "setup.url": "Server URL",
  "setup.urlPlaceholder": "https://music.example.org",
  "setup.username": "Username",
  "setup.password": "Password",
  "setup.name": "Name (optional)",
  "setup.connect": "Connect",
  "setup.connecting": "Connecting…",
  "setup.errorUrl": "Enter the server URL, including https://",
  "setup.errorCredentials": "Enter your username and password",
  "setup.failed": "Couldn't connect: {message}",

  // Top bar
  "search.placeholder": "Search library",
  "search.local": "In your library",
  "search.server": "More from the server",
  "search.noResults": "No matches for “{query}”",
  "search.tracks": "Songs",
  "search.albums": "Albums",
  "search.artists": "Artists",
  "search.playlists": "Playlists",
  "search.searching": "Searching the server…",
  "jobs.title": "Library activity",
  "jobs.idle": "Nothing running",
  "jobs.running": "{count} running",
  "jobs.problems": "{count} problems",
  "jobs.finishedWithProblems": "Finished with problems",
  "jobs.cancel": "Cancel",
  "jobs.pause": "Pause",
  "jobs.resume": "Resume",
  "jobs.retry": "Retry",
  "jobs.dismiss": "Dismiss",
  "jobs.dismissAll": "Dismiss all",
  "jobs.problemsHeading": "Problems",
  "jobs.jobsHeading": "Jobs",
  "jobs.progress": "{done} of {total}",
  "jobs.progressUnknown": "{done} done",
  "jobs.failedCount": "{failed} failed",
  "job.state.queued": "Queued",
  "job.state.running": "Running",
  "job.state.paused": "Paused",
  "job.state.done": "Done",
  "job.state.failed": "Finished with problems",
  "job.state.cancelled": "Cancelled",
  "sync.syncing": "Syncing library: {phase}",
  "sync.done": "Library up to date",

  // Player bar
  "player.nothingPlaying": "Nothing playing",
  "player.nothingPlayingHint": "Pick an album or press Ctrl+K to search.",
  "player.play": "Play",
  "player.pause": "Pause",
  "player.next": "Next",
  "player.previous": "Previous",
  "player.shuffle": "Shuffle",
  "player.repeat": "Repeat",
  "player.repeatOff": "Repeat off",
  "player.repeatAll": "Repeat all",
  "player.repeatOne": "Repeat one",
  "player.autoplay": "Autoplay",
  "player.volume": "Volume",
  "player.mute": "Mute",
  "player.love": "Love",
  "player.unlove": "Unlove",
  "player.rate": "Rate",
  "player.connect": "Play on…",
  "player.queue": "Queue",
  "player.lyrics": "Lyrics",
  "player.fullscreen": "Fullscreen player",
  "player.miniPlayer": "Mini player",
  "player.resume": "{device} was playing {track} · Resume here",
  "player.resumeAction": "Resume here",
  "player.resumeDismiss": "Dismiss",
  "player.seek": "Seek",
  "player.buffering": "Buffering…",
  "player.playingOn": "Playing on {device}",
  "player.sleepTimer": "Sleep timer",
  "player.sleepTimerOff": "Off",
  "player.sleepTimerMinutes": "{minutes} minutes",
  "player.sleepTimerEndOfTrack": "Stop at end of track",
  "player.sleepTimerActive": "Sleep in {remaining}",
  "player.batterySaver": "Battery saver",

  // Connect
  "connect.title": "Play on",
  "connect.thisDevice": "This device",
  "connect.playing": "Playing",
  "connect.ready": "Ready",
  "connect.preparing": "Preparing…",
  "connect.noDevices": "No other devices are connected. Open Hocket on another device signed in to the same server.",
  "connect.tier.local": "Not connected",
  "connect.tier.lan": "Connected on this network",
  "connect.tier.coordinator": "Connected through coordinator",
  "connect.peers": "{count} devices",

  // Queue
  "queue.title": "Queue",
  "queue.recent": "Recent",
  "queue.history": "Played",
  "queue.nowPlaying": "Now playing",
  "queue.playingNext": "Playing next",
  "queue.continuingFrom": "Continuing from {context}",
  "queue.upcoming": "Up next",
  "queue.empty": "Nothing is playing. Play an album, a playlist or a song to fill the queue.",
  "queue.more": "and {count} more",
  "queue.clear": "Clear queue",
  "queue.clearInsertions": "Clear playing next",
  "queue.remove": "Remove from queue",
  "queue.jump": "Play from here",
  "queue.autoplayFrom": "Autoplay · {reason}",
  "queue.mode.apple": "Playing-next list",
  "queue.mode.youtube": "Splice into context",
  "queue.unavailable": "Couldn't play on this device",
  "savedQueues.empty": "Queues you replace are kept here for 30 days. Pin one to keep it.",
  "savedQueues.pin": "Pin",
  "savedQueues.unpin": "Unpin",
  "savedQueues.restore": "Restore",
  "savedQueues.delete": "Delete",
  "savedQueues.saveAsPlaylist": "Save as playlist…",
  "savedQueues.tracks": "{count} tracks",
  "savedQueues.pinned": "Pinned",

  // Lyrics
  "lyrics.title": "Lyrics",
  "lyrics.none": "No lyrics for this track.",
  "lyrics.noneHint": "Turn on external lyrics in Settings to search other sources.",
  "lyrics.nothingPlaying": "Lyrics appear here while something plays.",
  "lyrics.offset": "Offset",
  "lyrics.offsetReset": "Reset",
  "lyrics.tier.syllable": "Word-synced",
  "lyrics.tier.line": "Line-synced",
  "lyrics.tier.unsynced": "Unsynced",
  "lyrics.source.server": "From the server",
  "lyrics.source.external": "From an external source",
  "lyrics.source.embedded": "Embedded",
  "lyrics.collapse": "Collapse lyrics",
  "lyrics.expand": "Expand lyrics",
  "queue.collapse": "Collapse queue",
  "queue.expand": "Expand queue",

  // Fullscreen
  "fullscreen.upNext": "Up next",
  "fullscreen.related": "Related",
  "fullscreen.lyrics": "Lyrics",
  "fullscreen.exit": "Exit fullscreen",
  "fullscreen.relatedEmpty": "Nothing related yet. Related tracks come from sonic similarity and the server's similar-songs endpoints.",
  "related.provider.sonicSimilarity": "Sonic similarity",
  "related.provider.similarSongs": "Similar songs",
  "related.provider.topSongs": "Top songs",
  "related.provider.random": "Random",
  "related.provider.savedFilter": "Saved filter",
  "related.score": "{score}% match",

  // Library views
  "home.title": "Home",
  "home.recentlyPlayed": "Recently played",
  "home.recentlyAdded": "Recently added",
  "home.mostPlayed": "Most played",
  "home.random": "Something different",
  "home.empty": "Your library is syncing. Albums appear here as soon as they land.",
  "albums.title": "Albums",
  "albums.empty": "No albums yet. Library sync fills this list; check the activity indicator top right.",
  "artists.title": "Artists",
  "artists.empty": "No artists yet. Library sync fills this list.",
  "playlists.title": "Playlists",
  "playlists.empty": "No playlists yet. Select some songs and choose Add to playlist.",
  "playlists.new": "New playlist",
  "playlists.smart": "Smart playlist",
  "playlists.readOnly": "Smart playlists are managed by their rules; edit the .nsp file to change them.",
  "playlists.owner": "by {owner}",
  "songs.title": "Songs",
  "songs.empty": "No songs yet. Library sync fills this list.",
  "genres.title": "Genres",
  "genres.empty": "No genres yet. Library sync fills this list.",
  "genres.count": "{albums} albums · {songs} songs",
  "album.play": "Play",
  "album.shuffle": "Shuffle",
  "album.tracks": "{count} tracks · {duration}",
  "artist.albums": "Albums",
  "artist.topSongs": "Top songs",
  "artist.albumsCount": "{albums} albums · {songs} songs",
  "playlist.tracks": "{count} tracks · {duration}",
  "downloads.title": "Downloads",
  "downloads.empty": "Nothing downloaded. Right-click an album, playlist or song and choose Download to keep it offline.",
  "downloads.usage": "Downloads {downloads} · Stream cache {cache} · Images {images}",
  "downloads.clearCache": "Clear stream cache",
  "downloads.remove": "Remove download",
  "downloads.progress": "{done} of {total} files",
  "downloads.transcoded": "Transcoded",
  "stats.title": "Listening stats",
  "stats.period": "Last {days} days",
  "stats.plays": "{count} plays",
  "stats.time": "{hours} hours listened",
  "stats.topTracks": "Top tracks",
  "stats.topAlbums": "Top albums",
  "stats.topArtists": "Top artists",
  "stats.byHour": "By hour of day",
  "stats.byWeekday": "By weekday",
  "stats.empty": "Play something and your listening history builds here, from local play history.",

  // Filters
  "filters.title": "Filters",
  "filters.new": "New filter",
  "filters.empty": "No saved filters. Create one to slice your library by any field, including downloaded state and sonic attributes.",
  "filters.builder": "Filter builder",
  "filters.name": "Name",
  "filters.matchAll": "All of",
  "filters.matchAny": "Any of",
  "filters.addRule": "Add rule",
  "filters.addGroup": "Add group",
  "filters.removeRule": "Remove",
  "filters.count": "{count} matching tracks",
  "filters.serverExpressible": "Can be pushed to the server as a smart playlist",
  "filters.localOnly": "Local only: {fields} aren't expressible in NSP",
  "filters.save": "Save",
  "filters.play": "Play",
  "filters.smartPlaylist": "Create smart playlist",
  "filters.staticPlaylist": "Create static playlist",
  "filters.exportNsp": "Export .nsp…",
  "filters.sort": "Sort",
  "filters.descending": "Descending",
  "filters.limit": "Limit",
  "filters.delete": "Delete filter",
  "filters.exported": "Exported to {path}",
  "filters.smartUnavailable": "Needs the native API (behind a capability flag)",
  "filters.sample": "Sample",

  // Settings
  "settings.title": "Settings",
  "settings.scope.synced": "Synced",
  "settings.scope.local": "This device",
  "settings.section.general": "General",
  "settings.section.audio": "Audio",
  "settings.section.transcoding": "Transcoding",
  "settings.section.connect": "Connect",
  "settings.section.storage": "Storage",
  "settings.section.lyrics": "Lyrics",
  "settings.section.appearance": "Appearance",
  "settings.section.customisation": "Customisation",
  "settings.section.shortcuts": "Keyboard shortcuts",
  "settings.section.backup": "Backup",
  "settings.section.diagnostics": "Diagnostics",
  "settings.section.about": "About",
  "settings.replayGain": "ReplayGain",
  "settings.replayGain.off": "Off",
  "settings.replayGain.track": "Track",
  "settings.replayGain.album": "Album",
  "settings.replayGain.auto": "Auto (album when playing an album)",
  "settings.replayGainPreamp": "Preamp",
  "settings.normalisation": "Queue-wide normalisation",
  "settings.eq": "Equalizer",
  "settings.eqPreamp": "EQ preamp",
  "settings.eqPreset": "Preset",
  "settings.eqFlat": "Flat",
  "settings.eqReset": "Reset bands",
  "settings.outputDevice": "Output device",
  "settings.outputDefault": "System default",
  "settings.exclusive": "Exclusive mode (bit-perfect where supported)",
  "settings.gapless": "Gapless playback",
  "settings.refreshDevices": "Refresh",
  "settings.transcodingNetwork": "Profile for this network",
  "settings.transcodingFormat": "Format",
  "settings.transcodingOriginal": "Original",
  "settings.transcodingBitrate": "Max bitrate",
  "settings.transcodingUnlimited": "Unlimited",
  "settings.transcodingCannotDecode": "Always transcode (comma-separated suffixes)",
  "settings.coordinatorUrl": "Coordinator URL",
  "settings.coordinatorConnect": "Connect",
  "settings.coordinatorDisconnect": "Disconnect",
  "settings.lanDiscovery": "Find devices on this network (mDNS)",
  "settings.deviceName": "This device",
  "settings.storage": "Storage",
  "settings.storageWarn": "Warn when downloads exceed",
  "settings.savedQueueCap": "Keep up to {n} recent queues",
  "settings.batterySaver": "Battery saver mode",
  "settings.batterySaverAuto": "Engage automatically on battery",
  "settings.batterySaverNow": "Battery saver is on: static background, lyrics at 30 fps, small artwork, prefetch paused.",
  "settings.externalLyrics": "Fetch lyrics from external sources",
  "settings.externalLyricsPrivacy": "Off by default: enabling this sends the title and artist of what you're listening to to a third-party lyrics service. Everything fetched is cached.",
  "settings.theme": "Theme",
  "settings.theme.system": "System",
  "settings.theme.light": "Light",
  "settings.theme.dark": "Dark",
  "settings.accent": "Accent colour",
  "settings.dynamicAccent": "Dynamic accent from artwork",
  "settings.animatedBackground": "Animated background in the fullscreen player",
  "settings.closeToTray": "Keep running in the tray when the window is closed",
  "settings.sidebarItems": "Sidebar items",
  "settings.contextMenuItems": "Context menu items",
  "settings.mediaSessionButtons": "Media session buttons",
  "settings.customiseHint": "Drag to reorder. Unchecked items are hidden.",
  "settings.shortcutsHint": "Click a shortcut and press the new keys. Escape cancels, Backspace clears.",
  "settings.shortcutConflict": "Also bound to {action}",
  "settings.shortcutReset": "Reset",
  "settings.shortcutResetAll": "Reset all shortcuts",
  "settings.shortcutRecording": "Press keys…",
  "settings.exportConfig": "Export configuration…",
  "settings.exportConfigSecrets": "Include server passwords",
  "settings.importConfig": "Import configuration…",
  "settings.importConfirm": "Importing replaces your settings, filters and shortcuts on this device. Continue?",
  "settings.copyDiagnostics": "Copy diagnostics",
  "settings.diagnosticsCopied": "Diagnostics copied to the clipboard",
  "settings.configExported": "Configuration exported",
  "settings.about": "Hocket {version} · Core {core} · Electron {electron}",
  "settings.licence": "Licensed under the GNU Affero General Public License v3.0. The lyric renderer (AMLL) is AGPL-3.0; Kawarp is MIT; playwire is MIT OR Apache-2.0; Symphonia is MPL-2.0.",
  "settings.licenceOpen": "View licence",
  "settings.sourceOpen": "Source code",
  "settings.autoplayChain": "Autoplay sources (in order)",
  "settings.autoplayMinSimilarity": "Minimum similarity",
  "settings.autoplaySeedWindow": "Seed from the last {n} tracks",
  "settings.queueMode": "Queue insertion mode",
  "settings.ratingBridge": "Mark as loved when rated at least",
  "settings.ratingBridgeOff": "Never",
  "settings.settingsSync": "Sync settings between devices",
  "settings.servers": "Servers",
  "settings.serverRemove": "Remove server",
  "settings.serverResync": "Resync library",
  "settings.serverFullResync": "Full reconcile",
  "settings.serverUnreachable": "Unreachable",
  "settings.serverVersion": "Navidrome {version}",
  "settings.serverBelowFloor": "Below the 0.63.0 minimum",
  "settings.language": "Language",
  "settings.mediaSessionState.attached": "OS media controls: attached",
  "settings.mediaSessionState.unavailable": "OS media controls: unavailable on this build",

  // Actions (labels used for local ui.* actions and default keymap)
  "action.palette": "Command palette",
  "action.search": "Search",
  "action.togglePlay": "Play / pause",
  "action.seekBack": "Seek back 10 s",
  "action.seekForward": "Seek forward 10 s",
  "action.previous": "Previous track",
  "action.next": "Next track",
  "action.toggleQueue": "Toggle queue panel",
  "action.toggleLyrics": "Toggle lyrics panel",
  "action.fullscreen": "Fullscreen player",
  "action.miniPlayer": "Mini player",
  "action.rate0": "Clear rating",
  "action.rate1": "Rate 1 star",
  "action.rate2": "Rate 2 stars",
  "action.rate3": "Rate 3 stars",
  "action.rate4": "Rate 4 stars",
  "action.rate5": "Rate 5 stars",
  "action.undo": "Undo",
  "action.redo": "Redo",
  "action.selectAll": "Select all",
  "action.delete": "Remove from playlist or queue",
  "action.escape": "Close / clear selection",
  "action.settings": "Settings",
  "action.shuffle": "Toggle shuffle",
  "action.repeat": "Cycle repeat",
  "action.volumeUp": "Volume up",
  "action.volumeDown": "Volume down",
  "action.love": "Love current track",
  "action.back": "Back",
  "action.forward": "Forward",
  "action.goToAlbum": "Go to album",
  "action.goToArtist": "Go to artist",
  "action.play": "Play",
  "action.playNext": "Play next",
  "action.playLater": "Play later",
  "action.addToPlaylist": "Add to playlist",
  "action.download": "Download",
  "action.removeDownload": "Remove download",
  "action.showInFolder": "Show in folder",
  "action.info": "Details",
  "action.newPlaylist": "New playlist…",
  "action.removeFromPlaylist": "Remove from playlist",
  "action.renamePlaylist": "Rename playlist…",
  "action.deletePlaylist": "Delete playlist",
  "action.openDownloads": "Open downloads",
  "action.openStats": "Open stats",
  "action.openFilters": "Open filters",
  "action.newFilter": "New filter",
  "action.sleepTimer": "Sleep timer",
  "action.copyDiagnostics": "Copy diagnostics",
  "action.quit": "Quit Hocket",
  "action.toggleAutoplay": "Toggle autoplay",
  "action.playOn": "Play on…",
  "action.resumeHere": "Resume here",
  "action.clearQueue": "Clear queue",
  "action.showMain": "Show Hocket",

  // Palette
  "palette.placeholder": "Search songs, albums, artists, playlists, actions…",
  "palette.results": "Results",
  "palette.actions": "Actions",
  "palette.empty": "Nothing matches",

  // Selection
  "selection.count": "{count} selected",
  "selection.allMatching": "All {count} matching tracks selected",
  "selection.clear": "Clear selection",
  "selection.restoreToast": "Selection cleared",
  "selection.restore": "Restore",

  // Dialogs
  "dialog.ok": "OK",
  "dialog.cancel": "Cancel",
  "dialog.confirm": "Confirm",
  "dialog.delete": "Delete",
  "dialog.playlistName": "Playlist name",
  "dialog.newPlaylist": "New playlist",
  "dialog.renamePlaylist": "Rename playlist",
  "dialog.deletePlaylist": "Delete “{name}”? This can't be undone.",
  "dialog.deleteDownload": "Remove the download of “{name}”? The files are deleted from this device.",
  "dialog.addToPlaylist": "Add to playlist",
  "dialog.exportNsp": "Export smart playlist rules",
  "dialog.exportConfig": "Export configuration",
  "dialog.importConfig": "Import configuration",
  "dialog.saveQueueAsPlaylist": "Save queue as playlist",
  "dialog.removeServer": "Remove “{name}”? Downloads and the local library mirror for it are deleted.",

  // Toasts and undo
  "toast.undo": "Undo",
  "toast.redo": "Redo",
  "toast.undone": "Undone: {label}",
  "toast.redone": "Redone: {label}",
  "toast.copied": "Copied",
  "toast.addedToQueue": "Added to queue",
  "toast.playingNext": "Playing next",
  "toast.addedToPlaylist": "Added to {playlist}",

  // Table columns
  "col.title": "Title",
  "col.artist": "Artist",
  "col.album": "Album",
  "col.duration": "Time",
  "col.year": "Year",
  "col.genre": "Genre",
  "col.rating": "Rating",
  "col.plays": "Plays",
  "col.added": "Added",
  "col.bpm": "BPM",
  "col.track": "#",
  "col.love": "Love",
  "col.offline": "Offline",

  // Sort
  "sort.default": "Default",
  "sort.title": "Title",
  "sort.artist": "Artist",
  "sort.album": "Album",
  "sort.year": "Year",
  "sort.dateAdded": "Recently added",
  "sort.rating": "Rating",
  "sort.playCount": "Most played",
  "sort.duration": "Duration",
  "sort.random": "Random",
  "sort.bpm": "BPM",
  "sort.energy": "Energy",
  "sort.label": "Sort by {sort}",

  // Misc
  "misc.loading": "Loading…",
  "misc.offline": "Offline",
  "misc.unknownArtist": "Unknown artist",
  "misc.unknownAlbum": "Unknown album",
  "misc.tracks": "{count} tracks",
  "misc.close": "Close",
  "misc.more": "More",
  "misc.nowPlaying": "Now playing",
  "misc.minimize": "Minimize",
  "misc.maximize": "Maximize",
  "misc.restore": "Restore",
  "misc.hoursMinutes": "{h} h {m} min",
  "misc.minutes": "{m} min",
  "misc.notice.dismiss": "Dismiss",
  "mini.title": "Hocket mini player",
  "mini.back": "Back to Hocket",
  "mini.pin": "Keep on top",
  "tray.show": "Show Hocket",
  "tray.quit": "Quit",
} as const;

export type StringId = keyof typeof STRINGS;

export function t(id: StringId, params?: Record<string, string | number>): string {
  const raw: string = STRINGS[id];
  if (!params) return raw;
  return raw.replace(/\{(\w+)\}/g, (_m, key: string) => {
    const v = params[key];
    return v === undefined ? `{${key}}` : String(v);
  });
}

export function hasString(id: string): id is StringId {
  return Object.prototype.hasOwnProperty.call(STRINGS, id);
}
